// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messagepath/v1/carousels.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Messagepath.V1 {

  /// <summary>Holder for reflection information generated from messagepath/v1/carousels.proto</summary>
  public static partial class CarouselsReflection {

    #region Descriptor
    /// <summary>File descriptor for messagepath/v1/carousels.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CarouselsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tZXNzYWdlcGF0aC92MS9jYXJvdXNlbHMucHJvdG8SFWNvbW1vbi5tZXNz",
            "YWdlcGF0aC52MRoSY29tbW9uX21vZGVsLnByb3RvGhlwcm90b2J1Zl92YWxp",
            "ZGF0aW9uLnByb3RvGh5tZXNzYWdlcGF0aC92MS9rZXlib2FyZHMucHJvdG8a",
            "IW1lc3NhZ2VwYXRoL3YxL2xpbmtfbWVzc2FnZS5wcm90byJdChlDYXJvdXNl",
            "bE1lc3NhZ2VBdHRhY2htZW50EkAKBWl0ZW1zGAEgAygLMiMuY29tbW9uLm1l",
            "c3NhZ2VwYXRoLnYxLkNhcm91c2VsSXRlbUIMyp0lCAgBeAGAAegHInsKDENh",
            "cm91c2VsSXRlbRIkCgptZXNzYWdlX2lkGAEgASgLMg4uY29tbW9uLlhpVXVp",
            "ZEgAEj0KB2NvbnRlbnQYAiABKAsyKi5jb21tb24ubWVzc2FnZXBhdGgudjEu",
            "Q2Fyb3VzZWxJdGVtQ29udGVudEgAQgYKBGl0ZW0itgEKE0Nhcm91c2VsSXRl",
            "bUNvbnRlbnQSRgoTa2V5Ym9hcmRfYXR0YWNobWVudBgeIAEoCzIpLmNvbW1v",
            "bi5tZXNzYWdlcGF0aC52MS5LZXlib2FyZEF0dGFjaG1lbnQSTwoXbGlua19t",
            "ZXNzYWdlX2F0dGFjaG1lbnQYHyABKAsyLC5jb21tb24ubWVzc2FnZXBhdGgu",
            "djEuTGlua01lc3NhZ2VBdHRhY2htZW50SABCBgoEdHlwZUJ6Chljb20ua2lr",
            "Lm1lc3NhZ2VwYXRoLm1vZGVsWlZnaXRodWIuY29tL2tpa2ludGVyYWN0aXZl",
            "L3hpcGhpYXMtbW9kZWwtY29tbW9uL2dlbmVyYXRlZC9nby9tZXNzYWdlcGF0",
            "aC92MTttZXNzYWdlcGF0aKICBE1QVEhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonModelReflection.Descriptor, global::Kik.Validation.ProtobufValidationReflection.Descriptor, global::Common.Messagepath.V1.KeyboardsReflection.Descriptor, global::Common.Messagepath.V1.LinkMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Messagepath.V1.CarouselMessageAttachment), global::Common.Messagepath.V1.CarouselMessageAttachment.Parser, new[]{ "Items" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Messagepath.V1.CarouselItem), global::Common.Messagepath.V1.CarouselItem.Parser, new[]{ "MessageId", "Content" }, new[]{ "Item" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Messagepath.V1.CarouselItemContent), global::Common.Messagepath.V1.CarouselItemContent.Parser, new[]{ "KeyboardAttachment", "LinkMessageAttachment" }, new[]{ "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CarouselMessageAttachment defines the properties required to render a carousel message sent by a
  /// bot. A carousel message contains multiple pieces of content that can be scrolled through
  /// horizontally.
  /// </summary>
  public sealed partial class CarouselMessageAttachment : pb::IMessage<CarouselMessageAttachment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CarouselMessageAttachment> _parser = new pb::MessageParser<CarouselMessageAttachment>(() => new CarouselMessageAttachment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CarouselMessageAttachment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Messagepath.V1.CarouselsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselMessageAttachment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselMessageAttachment(CarouselMessageAttachment other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselMessageAttachment Clone() {
      return new CarouselMessageAttachment(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Common.Messagepath.V1.CarouselItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Common.Messagepath.V1.CarouselItem.Parser);
    private readonly pbc::RepeatedField<global::Common.Messagepath.V1.CarouselItem> items_ = new pbc::RepeatedField<global::Common.Messagepath.V1.CarouselItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Common.Messagepath.V1.CarouselItem> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CarouselMessageAttachment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CarouselMessageAttachment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CarouselMessageAttachment other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CarouselItem defines a single piece of content in a carousel.
  /// </summary>
  public sealed partial class CarouselItem : pb::IMessage<CarouselItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CarouselItem> _parser = new pb::MessageParser<CarouselItem>(() => new CarouselItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CarouselItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Messagepath.V1.CarouselsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItem(CarouselItem other) : this() {
      switch (other.ItemCase) {
        case ItemOneofCase.MessageId:
          MessageId = other.MessageId.Clone();
          break;
        case ItemOneofCase.Content:
          Content = other.Content.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItem Clone() {
      return new CarouselItem(this);
    }

    /// <summary>Field number for the "message_id" field.</summary>
    public const int MessageIdFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiUuid MessageId {
      get { return itemCase_ == ItemOneofCase.MessageId ? (global::Common.XiUuid) item_ : null; }
      set {
        item_ = value;
        itemCase_ = value == null ? ItemOneofCase.None : ItemOneofCase.MessageId;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Messagepath.V1.CarouselItemContent Content {
      get { return itemCase_ == ItemOneofCase.Content ? (global::Common.Messagepath.V1.CarouselItemContent) item_ : null; }
      set {
        item_ = value;
        itemCase_ = value == null ? ItemOneofCase.None : ItemOneofCase.Content;
      }
    }

    private object item_;
    /// <summary>Enum of possible cases for the "item" oneof.</summary>
    public enum ItemOneofCase {
      None = 0,
      MessageId = 1,
      Content = 2,
    }
    private ItemOneofCase itemCase_ = ItemOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemOneofCase ItemCase {
      get { return itemCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItem() {
      itemCase_ = ItemOneofCase.None;
      item_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CarouselItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CarouselItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MessageId, other.MessageId)) return false;
      if (!object.Equals(Content, other.Content)) return false;
      if (ItemCase != other.ItemCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (itemCase_ == ItemOneofCase.MessageId) hash ^= MessageId.GetHashCode();
      if (itemCase_ == ItemOneofCase.Content) hash ^= Content.GetHashCode();
      hash ^= (int) itemCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (itemCase_ == ItemOneofCase.MessageId) {
        output.WriteRawTag(10);
        output.WriteMessage(MessageId);
      }
      if (itemCase_ == ItemOneofCase.Content) {
        output.WriteRawTag(18);
        output.WriteMessage(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (itemCase_ == ItemOneofCase.MessageId) {
        output.WriteRawTag(10);
        output.WriteMessage(MessageId);
      }
      if (itemCase_ == ItemOneofCase.Content) {
        output.WriteRawTag(18);
        output.WriteMessage(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (itemCase_ == ItemOneofCase.MessageId) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageId);
      }
      if (itemCase_ == ItemOneofCase.Content) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CarouselItem other) {
      if (other == null) {
        return;
      }
      switch (other.ItemCase) {
        case ItemOneofCase.MessageId:
          if (MessageId == null) {
            MessageId = new global::Common.XiUuid();
          }
          MessageId.MergeFrom(other.MessageId);
          break;
        case ItemOneofCase.Content:
          if (Content == null) {
            Content = new global::Common.Messagepath.V1.CarouselItemContent();
          }
          Content.MergeFrom(other.Content);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Common.XiUuid subBuilder = new global::Common.XiUuid();
            if (itemCase_ == ItemOneofCase.MessageId) {
              subBuilder.MergeFrom(MessageId);
            }
            input.ReadMessage(subBuilder);
            MessageId = subBuilder;
            break;
          }
          case 18: {
            global::Common.Messagepath.V1.CarouselItemContent subBuilder = new global::Common.Messagepath.V1.CarouselItemContent();
            if (itemCase_ == ItemOneofCase.Content) {
              subBuilder.MergeFrom(Content);
            }
            input.ReadMessage(subBuilder);
            Content = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Common.XiUuid subBuilder = new global::Common.XiUuid();
            if (itemCase_ == ItemOneofCase.MessageId) {
              subBuilder.MergeFrom(MessageId);
            }
            input.ReadMessage(subBuilder);
            MessageId = subBuilder;
            break;
          }
          case 18: {
            global::Common.Messagepath.V1.CarouselItemContent subBuilder = new global::Common.Messagepath.V1.CarouselItemContent();
            if (itemCase_ == ItemOneofCase.Content) {
              subBuilder.MergeFrom(Content);
            }
            input.ReadMessage(subBuilder);
            Content = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CarouselItemContent : pb::IMessage<CarouselItemContent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CarouselItemContent> _parser = new pb::MessageParser<CarouselItemContent>(() => new CarouselItemContent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CarouselItemContent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Messagepath.V1.CarouselsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItemContent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItemContent(CarouselItemContent other) : this() {
      keyboardAttachment_ = other.keyboardAttachment_ != null ? other.keyboardAttachment_.Clone() : null;
      switch (other.TypeCase) {
        case TypeOneofCase.LinkMessageAttachment:
          LinkMessageAttachment = other.LinkMessageAttachment.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarouselItemContent Clone() {
      return new CarouselItemContent(this);
    }

    /// <summary>Field number for the "keyboard_attachment" field.</summary>
    public const int KeyboardAttachmentFieldNumber = 30;
    private global::Common.Messagepath.V1.KeyboardAttachment keyboardAttachment_;
    /// <summary>
    /// Each carousel item can have its own keyboard attachment.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Messagepath.V1.KeyboardAttachment KeyboardAttachment {
      get { return keyboardAttachment_; }
      set {
        keyboardAttachment_ = value;
      }
    }

    /// <summary>Field number for the "link_message_attachment" field.</summary>
    public const int LinkMessageAttachmentFieldNumber = 31;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Messagepath.V1.LinkMessageAttachment LinkMessageAttachment {
      get { return typeCase_ == TypeOneofCase.LinkMessageAttachment ? (global::Common.Messagepath.V1.LinkMessageAttachment) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.LinkMessageAttachment;
      }
    }

    private object type_;
    /// <summary>Enum of possible cases for the "type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      LinkMessageAttachment = 31,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CarouselItemContent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CarouselItemContent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(KeyboardAttachment, other.KeyboardAttachment)) return false;
      if (!object.Equals(LinkMessageAttachment, other.LinkMessageAttachment)) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (keyboardAttachment_ != null) hash ^= KeyboardAttachment.GetHashCode();
      if (typeCase_ == TypeOneofCase.LinkMessageAttachment) hash ^= LinkMessageAttachment.GetHashCode();
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (keyboardAttachment_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(KeyboardAttachment);
      }
      if (typeCase_ == TypeOneofCase.LinkMessageAttachment) {
        output.WriteRawTag(250, 1);
        output.WriteMessage(LinkMessageAttachment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (keyboardAttachment_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(KeyboardAttachment);
      }
      if (typeCase_ == TypeOneofCase.LinkMessageAttachment) {
        output.WriteRawTag(250, 1);
        output.WriteMessage(LinkMessageAttachment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (keyboardAttachment_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(KeyboardAttachment);
      }
      if (typeCase_ == TypeOneofCase.LinkMessageAttachment) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LinkMessageAttachment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CarouselItemContent other) {
      if (other == null) {
        return;
      }
      if (other.keyboardAttachment_ != null) {
        if (keyboardAttachment_ == null) {
          KeyboardAttachment = new global::Common.Messagepath.V1.KeyboardAttachment();
        }
        KeyboardAttachment.MergeFrom(other.KeyboardAttachment);
      }
      switch (other.TypeCase) {
        case TypeOneofCase.LinkMessageAttachment:
          if (LinkMessageAttachment == null) {
            LinkMessageAttachment = new global::Common.Messagepath.V1.LinkMessageAttachment();
          }
          LinkMessageAttachment.MergeFrom(other.LinkMessageAttachment);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 242: {
            if (keyboardAttachment_ == null) {
              KeyboardAttachment = new global::Common.Messagepath.V1.KeyboardAttachment();
            }
            input.ReadMessage(KeyboardAttachment);
            break;
          }
          case 250: {
            global::Common.Messagepath.V1.LinkMessageAttachment subBuilder = new global::Common.Messagepath.V1.LinkMessageAttachment();
            if (typeCase_ == TypeOneofCase.LinkMessageAttachment) {
              subBuilder.MergeFrom(LinkMessageAttachment);
            }
            input.ReadMessage(subBuilder);
            LinkMessageAttachment = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 242: {
            if (keyboardAttachment_ == null) {
              KeyboardAttachment = new global::Common.Messagepath.V1.KeyboardAttachment();
            }
            input.ReadMessage(KeyboardAttachment);
            break;
          }
          case 250: {
            global::Common.Messagepath.V1.LinkMessageAttachment subBuilder = new global::Common.Messagepath.V1.LinkMessageAttachment();
            if (typeCase_ == TypeOneofCase.LinkMessageAttachment) {
              subBuilder.MergeFrom(LinkMessageAttachment);
            }
            input.ReadMessage(subBuilder);
            LinkMessageAttachment = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
