// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entity/v1/entity_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Entity.V1 {

  /// <summary>Holder for reflection information generated from entity/v1/entity_common.proto</summary>
  public static partial class EntityCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for entity/v1/entity_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1lbnRpdHkvdjEvZW50aXR5X2NvbW1vbi5wcm90bxIQY29tbW9uLmVudGl0",
            "eS52MRoZcHJvdG9idWZfdmFsaWRhdGlvbi5wcm90bxoSY29tbW9uX21vZGVs",
            "LnByb3RvGh5lbnRpdHkvdjEvZWxlbWVudF9jb21tb24ucHJvdG8i7QEKCUVu",
            "dGl0eUtleRI0CgR0eXBlGAEgASgOMiYuY29tbW9uLmVudGl0eS52MS5FbnRp",
            "dHlLZXkuRW50aXR5VHlwZRIpCgh1c2VyX2ppZBgCIAEoCzIVLmNvbW1vbi5Y",
            "aUJhcmVVc2VySmlkSAASJwoJZ3JvdXBfamlkGAMgASgLMhIuY29tbW9uLlhp",
            "R3JvdXBKaWRIACJQCgpFbnRpdHlUeXBlEggKBFVTRVIQABIJCgVHUk9VUBAB",
            "EhUKEVVTRVJfUk9TVEVSX0VOVFJZEAISFgoSR1JPVVBfUk9TVEVSX0VOVFJZ",
            "EANCBAoCaWQi7wIKC0VudGl0eUdyb3VwEiYKAmlkGAEgASgLMhIuY29tbW9u",
            "LlhpR3JvdXBKaWRCBsqdJQIIARIxCgtiaW9fZWxlbWVudBhkIAEoCzIcLmNv",
            "bW1vbi5lbnRpdHkudjEuQmlvRWxlbWVudBJcCh5vcmlnaW5hbF9wcm9maWxl",
            "X3BpY19leHRlbnNpb24YZSABKAsyNC5jb21tb24uZW50aXR5LnYxLk9yaWdp",
            "bmFsUHJvZmlsZVBpY0V4dGVuc2lvbkVsZW1lbnQSYAogYmFja2dyb3VuZF9w",
            "cm9maWxlX3BpY19leHRlbnNpb24YZiABKAsyNi5jb21tb24uZW50aXR5LnYx",
            "LkJhY2tncm91bmRQcm9maWxlUGljRXh0ZW5zaW9uRWxlbWVudBJFChZtYXhf",
            "Z3JvdXBfc2l6ZV9lbGVtZW50GGcgASgLMiUuY29tbW9uLmVudGl0eS52MS5N",
            "YXhHcm91cFNpemVFbGVtZW50Iq4DCgpFbnRpdHlVc2VyEikKAmlkGAEgASgL",
            "MhUuY29tbW9uLlhpQmFyZVVzZXJKaWRCBsqdJQIIARIxCgtiaW9fZWxlbWVu",
            "dBhkIAEoCzIcLmNvbW1vbi5lbnRpdHkudjEuQmlvRWxlbWVudBJcCh5vcmln",
            "aW5hbF9wcm9maWxlX3BpY19leHRlbnNpb24YZSABKAsyNC5jb21tb24uZW50",
            "aXR5LnYxLk9yaWdpbmFsUHJvZmlsZVBpY0V4dGVuc2lvbkVsZW1lbnQSYAog",
            "YmFja2dyb3VuZF9wcm9maWxlX3BpY19leHRlbnNpb24YZiABKAsyNi5jb21t",
            "b24uZW50aXR5LnYxLkJhY2tncm91bmRQcm9maWxlUGljRXh0ZW5zaW9uRWxl",
            "bWVudBJDChRyZWdpc3RyYXRpb25fZWxlbWVudBhnIAEoCzIlLmNvbW1vbi5l",
            "bnRpdHkudjEuUmVnaXN0cmF0aW9uRWxlbWVudBI9ChFpbnRlcmVzdHNfZWxl",
            "bWVudBhoIAEoCzIiLmNvbW1vbi5lbnRpdHkudjEuSW50ZXJlc3RzRWxlbWVu",
            "dCLvAgoVRW50aXR5VXNlclJvc3RlckVudHJ5EikKAmlkGAEgASgLMhUuY29t",
            "bW9uLlhpQmFyZVVzZXJKaWRCBsqdJQIIARJCChRlbW9qaV9zdGF0dXNfZWxl",
            "bWVudBgCIAEoCzIkLmNvbW1vbi5lbnRpdHkudjEuRW1vamlTdGF0dXNFbGVt",
            "ZW50EjMKCHVzZXJuYW1lGAMgASgLMiEuY29tbW9uLmVudGl0eS52MS5Vc2Vy",
            "bmFtZUVsZW1lbnQSOgoMZGlzcGxheV9uYW1lGAQgASgLMiQuY29tbW9uLmVu",
            "dGl0eS52MS5EaXNwbGF5TmFtZUVsZW1lbnQSOAoLcHJvZmlsZV9waWMYBSAB",
            "KAsyIy5jb21tb24uZW50aXR5LnYxLlByb2ZpbGVQaWNFbGVtZW50EjwKDWJv",
            "dF9leHRlbnNpb24YBiABKAsyJS5jb21tb24uZW50aXR5LnYxLkJvdEV4dGVu",
            "c2lvbkVsZW1lbnQi1gIKFkVudGl0eUdyb3VwUm9zdGVyRW50cnkSJgoCaWQY",
            "ASABKAsyEi5jb21tb24uWGlHcm91cEppZEIGyp0lAggBEi8KBnB1YmxpYxgC",
            "IAEoCzIfLmNvbW1vbi5lbnRpdHkudjEuUHVibGljRWxlbWVudBI2Cgpncm91",
            "cF9jb2RlGAMgASgLMiIuY29tbW9uLmVudGl0eS52MS5Hcm91cENvZGVFbGVt",
            "ZW50EjYKCmdyb3VwX25hbWUYBCABKAsyIi5jb21tb24uZW50aXR5LnYxLkdy",
            "b3VwTmFtZUVsZW1lbnQSOAoLcHJvZmlsZV9waWMYBSABKAsyIy5jb21tb24u",
            "ZW50aXR5LnYxLlByb2ZpbGVQaWNFbGVtZW50EjkKB21lbWJlcnMYBiABKAsy",
            "KC5jb21tb24uZW50aXR5LnYxLkdyb3VwTWVtYmVyTGlzdEVsZW1lbnQilgQK",
            "CUVudGl0eUJvdBIpCgJpZBgBIAEoCzIVLmNvbW1vbi5YaUJhcmVVc2VySmlk",
            "QgbKnSUCCAESMQoLYmlvX2VsZW1lbnQYZCABKAsyHC5jb21tb24uZW50aXR5",
            "LnYxLkJpb0VsZW1lbnQSXAoeb3JpZ2luYWxfcHJvZmlsZV9waWNfZXh0ZW5z",
            "aW9uGGUgASgLMjQuY29tbW9uLmVudGl0eS52MS5PcmlnaW5hbFByb2ZpbGVQ",
            "aWNFeHRlbnNpb25FbGVtZW50EmAKIGJhY2tncm91bmRfcHJvZmlsZV9waWNf",
            "ZXh0ZW5zaW9uGGYgASgLMjYuY29tbW9uLmVudGl0eS52MS5CYWNrZ3JvdW5k",
            "UHJvZmlsZVBpY0V4dGVuc2lvbkVsZW1lbnQSQwoUcmVnaXN0cmF0aW9uX2Vs",
            "ZW1lbnQYZyABKAsyJS5jb21tb24uZW50aXR5LnYxLlJlZ2lzdHJhdGlvbkVs",
            "ZW1lbnQSOAoOYnlsaW5lX2VsZW1lbnQYyAEgASgLMh8uY29tbW9uLmVudGl0",
            "eS52MS5CeWxpbmVFbGVtZW50EjgKDnJhdGluZ19zdW1tYXJ5GMkBIAEoCzIf",
            "LmNvbW1vbi5lbnRpdHkudjEuUmF0aW5nU3VtbWFyeRIyCgd0cnVzdGVkGMoB",
            "IAEoCzIgLmNvbW1vbi5lbnRpdHkudjEuVHJ1c3RlZEVsZW1lbnRCbQoUY29t",
            "Lmtpay5lbnRpdHkubW9kZWxaTGdpdGh1Yi5jb20va2lraW50ZXJhY3RpdmUv",
            "eGlwaGlhcy1tb2RlbC1jb21tb24vZ2VuZXJhdGVkL2dvL2VudGl0eS92MTtl",
            "bnRpdHmgAQGiAgNFTlRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kik.Validation.ProtobufValidationReflection.Descriptor, global::Common.CommonModelReflection.Descriptor, global::Common.Entity.V1.ElementCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityKey), global::Common.Entity.V1.EntityKey.Parser, new[]{ "Type", "UserJid", "GroupJid" }, new[]{ "Id" }, new[]{ typeof(global::Common.Entity.V1.EntityKey.Types.EntityType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityGroup), global::Common.Entity.V1.EntityGroup.Parser, new[]{ "Id", "BioElement", "OriginalProfilePicExtension", "BackgroundProfilePicExtension", "MaxGroupSizeElement" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityUser), global::Common.Entity.V1.EntityUser.Parser, new[]{ "Id", "BioElement", "OriginalProfilePicExtension", "BackgroundProfilePicExtension", "RegistrationElement", "InterestsElement" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityUserRosterEntry), global::Common.Entity.V1.EntityUserRosterEntry.Parser, new[]{ "Id", "EmojiStatusElement", "Username", "DisplayName", "ProfilePic", "BotExtension" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityGroupRosterEntry), global::Common.Entity.V1.EntityGroupRosterEntry.Parser, new[]{ "Id", "Public", "GroupCode", "GroupName", "ProfilePic", "Members" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Entity.V1.EntityBot), global::Common.Entity.V1.EntityBot.Parser, new[]{ "Id", "BioElement", "OriginalProfilePicExtension", "BackgroundProfilePicExtension", "RegistrationElement", "BylineElement", "RatingSummary", "Trusted" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///**************************************************
  /// Key used by Entity Warehouse, Subscription Service, etc
  /// to explicitly identify entities
  ///**************************************************
  /// </summary>
  public sealed partial class EntityKey : pb::IMessage<EntityKey>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityKey> _parser = new pb::MessageParser<EntityKey>(() => new EntityKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityKey(EntityKey other) : this() {
      type_ = other.type_;
      switch (other.IdCase) {
        case IdOneofCase.UserJid:
          UserJid = other.UserJid.Clone();
          break;
        case IdOneofCase.GroupJid:
          GroupJid = other.GroupJid.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityKey Clone() {
      return new EntityKey(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Common.Entity.V1.EntityKey.Types.EntityType type_ = global::Common.Entity.V1.EntityKey.Types.EntityType.User;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.EntityKey.Types.EntityType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user_jid" field.</summary>
    public const int UserJidFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiBareUserJid UserJid {
      get { return idCase_ == IdOneofCase.UserJid ? (global::Common.XiBareUserJid) id_ : null; }
      set {
        id_ = value;
        idCase_ = value == null ? IdOneofCase.None : IdOneofCase.UserJid;
      }
    }

    /// <summary>Field number for the "group_jid" field.</summary>
    public const int GroupJidFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiGroupJid GroupJid {
      get { return idCase_ == IdOneofCase.GroupJid ? (global::Common.XiGroupJid) id_ : null; }
      set {
        id_ = value;
        idCase_ = value == null ? IdOneofCase.None : IdOneofCase.GroupJid;
      }
    }

    private object id_;
    /// <summary>Enum of possible cases for the "id" oneof.</summary>
    public enum IdOneofCase {
      None = 0,
      UserJid = 2,
      GroupJid = 3,
    }
    private IdOneofCase idCase_ = IdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdOneofCase IdCase {
      get { return idCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      idCase_ = IdOneofCase.None;
      id_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(UserJid, other.UserJid)) return false;
      if (!object.Equals(GroupJid, other.GroupJid)) return false;
      if (IdCase != other.IdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Common.Entity.V1.EntityKey.Types.EntityType.User) hash ^= Type.GetHashCode();
      if (idCase_ == IdOneofCase.UserJid) hash ^= UserJid.GetHashCode();
      if (idCase_ == IdOneofCase.GroupJid) hash ^= GroupJid.GetHashCode();
      hash ^= (int) idCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Common.Entity.V1.EntityKey.Types.EntityType.User) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (idCase_ == IdOneofCase.UserJid) {
        output.WriteRawTag(18);
        output.WriteMessage(UserJid);
      }
      if (idCase_ == IdOneofCase.GroupJid) {
        output.WriteRawTag(26);
        output.WriteMessage(GroupJid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Common.Entity.V1.EntityKey.Types.EntityType.User) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (idCase_ == IdOneofCase.UserJid) {
        output.WriteRawTag(18);
        output.WriteMessage(UserJid);
      }
      if (idCase_ == IdOneofCase.GroupJid) {
        output.WriteRawTag(26);
        output.WriteMessage(GroupJid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Common.Entity.V1.EntityKey.Types.EntityType.User) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (idCase_ == IdOneofCase.UserJid) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserJid);
      }
      if (idCase_ == IdOneofCase.GroupJid) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupJid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityKey other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Common.Entity.V1.EntityKey.Types.EntityType.User) {
        Type = other.Type;
      }
      switch (other.IdCase) {
        case IdOneofCase.UserJid:
          if (UserJid == null) {
            UserJid = new global::Common.XiBareUserJid();
          }
          UserJid.MergeFrom(other.UserJid);
          break;
        case IdOneofCase.GroupJid:
          if (GroupJid == null) {
            GroupJid = new global::Common.XiGroupJid();
          }
          GroupJid.MergeFrom(other.GroupJid);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Common.Entity.V1.EntityKey.Types.EntityType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Common.XiBareUserJid subBuilder = new global::Common.XiBareUserJid();
            if (idCase_ == IdOneofCase.UserJid) {
              subBuilder.MergeFrom(UserJid);
            }
            input.ReadMessage(subBuilder);
            UserJid = subBuilder;
            break;
          }
          case 26: {
            global::Common.XiGroupJid subBuilder = new global::Common.XiGroupJid();
            if (idCase_ == IdOneofCase.GroupJid) {
              subBuilder.MergeFrom(GroupJid);
            }
            input.ReadMessage(subBuilder);
            GroupJid = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Common.Entity.V1.EntityKey.Types.EntityType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Common.XiBareUserJid subBuilder = new global::Common.XiBareUserJid();
            if (idCase_ == IdOneofCase.UserJid) {
              subBuilder.MergeFrom(UserJid);
            }
            input.ReadMessage(subBuilder);
            UserJid = subBuilder;
            break;
          }
          case 26: {
            global::Common.XiGroupJid subBuilder = new global::Common.XiGroupJid();
            if (idCase_ == IdOneofCase.GroupJid) {
              subBuilder.MergeFrom(GroupJid);
            }
            input.ReadMessage(subBuilder);
            GroupJid = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EntityKey message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum EntityType {
        [pbr::OriginalName("USER")] User = 0,
        [pbr::OriginalName("GROUP")] Group = 1,
        [pbr::OriginalName("USER_ROSTER_ENTRY")] UserRosterEntry = 2,
        [pbr::OriginalName("GROUP_ROSTER_ENTRY")] GroupRosterEntry = 3,
      }

    }
    #endregion

  }

  public sealed partial class EntityGroup : pb::IMessage<EntityGroup>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityGroup> _parser = new pb::MessageParser<EntityGroup>(() => new EntityGroup());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityGroup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroup(EntityGroup other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      bioElement_ = other.bioElement_ != null ? other.bioElement_.Clone() : null;
      originalProfilePicExtension_ = other.originalProfilePicExtension_ != null ? other.originalProfilePicExtension_.Clone() : null;
      backgroundProfilePicExtension_ = other.backgroundProfilePicExtension_ != null ? other.backgroundProfilePicExtension_.Clone() : null;
      maxGroupSizeElement_ = other.maxGroupSizeElement_ != null ? other.maxGroupSizeElement_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroup Clone() {
      return new EntityGroup(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Common.XiGroupJid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiGroupJid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "bio_element" field.</summary>
    public const int BioElementFieldNumber = 100;
    private global::Common.Entity.V1.BioElement bioElement_;
    /// <summary>
    /// Use tag number range of [100-199] for elements sourced from profile service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BioElement BioElement {
      get { return bioElement_; }
      set {
        bioElement_ = value;
      }
    }

    /// <summary>Field number for the "original_profile_pic_extension" field.</summary>
    public const int OriginalProfilePicExtensionFieldNumber = 101;
    private global::Common.Entity.V1.OriginalProfilePicExtensionElement originalProfilePicExtension_;
    /// <summary>
    /// Original Profile Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.OriginalProfilePicExtensionElement OriginalProfilePicExtension {
      get { return originalProfilePicExtension_; }
      set {
        originalProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "background_profile_pic_extension" field.</summary>
    public const int BackgroundProfilePicExtensionFieldNumber = 102;
    private global::Common.Entity.V1.BackgroundProfilePicExtensionElement backgroundProfilePicExtension_;
    /// <summary>
    /// Background Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BackgroundProfilePicExtensionElement BackgroundProfilePicExtension {
      get { return backgroundProfilePicExtension_; }
      set {
        backgroundProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "max_group_size_element" field.</summary>
    public const int MaxGroupSizeElementFieldNumber = 103;
    private global::Common.Entity.V1.MaxGroupSizeElement maxGroupSizeElement_;
    /// <summary>
    /// Maximum Group Size
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.MaxGroupSizeElement MaxGroupSizeElement {
      get { return maxGroupSizeElement_; }
      set {
        maxGroupSizeElement_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityGroup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(BioElement, other.BioElement)) return false;
      if (!object.Equals(OriginalProfilePicExtension, other.OriginalProfilePicExtension)) return false;
      if (!object.Equals(BackgroundProfilePicExtension, other.BackgroundProfilePicExtension)) return false;
      if (!object.Equals(MaxGroupSizeElement, other.MaxGroupSizeElement)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (bioElement_ != null) hash ^= BioElement.GetHashCode();
      if (originalProfilePicExtension_ != null) hash ^= OriginalProfilePicExtension.GetHashCode();
      if (backgroundProfilePicExtension_ != null) hash ^= BackgroundProfilePicExtension.GetHashCode();
      if (maxGroupSizeElement_ != null) hash ^= MaxGroupSizeElement.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (maxGroupSizeElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(MaxGroupSizeElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (maxGroupSizeElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(MaxGroupSizeElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (bioElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BackgroundProfilePicExtension);
      }
      if (maxGroupSizeElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MaxGroupSizeElement);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityGroup other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Common.XiGroupJid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.bioElement_ != null) {
        if (bioElement_ == null) {
          BioElement = new global::Common.Entity.V1.BioElement();
        }
        BioElement.MergeFrom(other.BioElement);
      }
      if (other.originalProfilePicExtension_ != null) {
        if (originalProfilePicExtension_ == null) {
          OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
        }
        OriginalProfilePicExtension.MergeFrom(other.OriginalProfilePicExtension);
      }
      if (other.backgroundProfilePicExtension_ != null) {
        if (backgroundProfilePicExtension_ == null) {
          BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
        }
        BackgroundProfilePicExtension.MergeFrom(other.BackgroundProfilePicExtension);
      }
      if (other.maxGroupSizeElement_ != null) {
        if (maxGroupSizeElement_ == null) {
          MaxGroupSizeElement = new global::Common.Entity.V1.MaxGroupSizeElement();
        }
        MaxGroupSizeElement.MergeFrom(other.MaxGroupSizeElement);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiGroupJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (maxGroupSizeElement_ == null) {
              MaxGroupSizeElement = new global::Common.Entity.V1.MaxGroupSizeElement();
            }
            input.ReadMessage(MaxGroupSizeElement);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiGroupJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (maxGroupSizeElement_ == null) {
              MaxGroupSizeElement = new global::Common.Entity.V1.MaxGroupSizeElement();
            }
            input.ReadMessage(MaxGroupSizeElement);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityUser : pb::IMessage<EntityUser>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityUser> _parser = new pb::MessageParser<EntityUser>(() => new EntityUser());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityUser> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUser() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUser(EntityUser other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      bioElement_ = other.bioElement_ != null ? other.bioElement_.Clone() : null;
      originalProfilePicExtension_ = other.originalProfilePicExtension_ != null ? other.originalProfilePicExtension_.Clone() : null;
      backgroundProfilePicExtension_ = other.backgroundProfilePicExtension_ != null ? other.backgroundProfilePicExtension_.Clone() : null;
      registrationElement_ = other.registrationElement_ != null ? other.registrationElement_.Clone() : null;
      interestsElement_ = other.interestsElement_ != null ? other.interestsElement_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUser Clone() {
      return new EntityUser(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Common.XiBareUserJid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiBareUserJid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "bio_element" field.</summary>
    public const int BioElementFieldNumber = 100;
    private global::Common.Entity.V1.BioElement bioElement_;
    /// <summary>
    /// Use tag number range of [100-199] for elements sourced from profile service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BioElement BioElement {
      get { return bioElement_; }
      set {
        bioElement_ = value;
      }
    }

    /// <summary>Field number for the "original_profile_pic_extension" field.</summary>
    public const int OriginalProfilePicExtensionFieldNumber = 101;
    private global::Common.Entity.V1.OriginalProfilePicExtensionElement originalProfilePicExtension_;
    /// <summary>
    /// Original Profile Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.OriginalProfilePicExtensionElement OriginalProfilePicExtension {
      get { return originalProfilePicExtension_; }
      set {
        originalProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "background_profile_pic_extension" field.</summary>
    public const int BackgroundProfilePicExtensionFieldNumber = 102;
    private global::Common.Entity.V1.BackgroundProfilePicExtensionElement backgroundProfilePicExtension_;
    /// <summary>
    /// Background Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BackgroundProfilePicExtensionElement BackgroundProfilePicExtension {
      get { return backgroundProfilePicExtension_; }
      set {
        backgroundProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "registration_element" field.</summary>
    public const int RegistrationElementFieldNumber = 103;
    private global::Common.Entity.V1.RegistrationElement registrationElement_;
    /// <summary>
    /// Registration Element for user
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.RegistrationElement RegistrationElement {
      get { return registrationElement_; }
      set {
        registrationElement_ = value;
      }
    }

    /// <summary>Field number for the "interests_element" field.</summary>
    public const int InterestsElementFieldNumber = 104;
    private global::Common.Entity.V1.InterestsElement interestsElement_;
    /// <summary>
    /// User Interests Element 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.InterestsElement InterestsElement {
      get { return interestsElement_; }
      set {
        interestsElement_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityUser);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityUser other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(BioElement, other.BioElement)) return false;
      if (!object.Equals(OriginalProfilePicExtension, other.OriginalProfilePicExtension)) return false;
      if (!object.Equals(BackgroundProfilePicExtension, other.BackgroundProfilePicExtension)) return false;
      if (!object.Equals(RegistrationElement, other.RegistrationElement)) return false;
      if (!object.Equals(InterestsElement, other.InterestsElement)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (bioElement_ != null) hash ^= BioElement.GetHashCode();
      if (originalProfilePicExtension_ != null) hash ^= OriginalProfilePicExtension.GetHashCode();
      if (backgroundProfilePicExtension_ != null) hash ^= BackgroundProfilePicExtension.GetHashCode();
      if (registrationElement_ != null) hash ^= RegistrationElement.GetHashCode();
      if (interestsElement_ != null) hash ^= InterestsElement.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(RegistrationElement);
      }
      if (interestsElement_ != null) {
        output.WriteRawTag(194, 6);
        output.WriteMessage(InterestsElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(RegistrationElement);
      }
      if (interestsElement_ != null) {
        output.WriteRawTag(194, 6);
        output.WriteMessage(InterestsElement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (bioElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RegistrationElement);
      }
      if (interestsElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(InterestsElement);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityUser other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Common.XiBareUserJid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.bioElement_ != null) {
        if (bioElement_ == null) {
          BioElement = new global::Common.Entity.V1.BioElement();
        }
        BioElement.MergeFrom(other.BioElement);
      }
      if (other.originalProfilePicExtension_ != null) {
        if (originalProfilePicExtension_ == null) {
          OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
        }
        OriginalProfilePicExtension.MergeFrom(other.OriginalProfilePicExtension);
      }
      if (other.backgroundProfilePicExtension_ != null) {
        if (backgroundProfilePicExtension_ == null) {
          BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
        }
        BackgroundProfilePicExtension.MergeFrom(other.BackgroundProfilePicExtension);
      }
      if (other.registrationElement_ != null) {
        if (registrationElement_ == null) {
          RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
        }
        RegistrationElement.MergeFrom(other.RegistrationElement);
      }
      if (other.interestsElement_ != null) {
        if (interestsElement_ == null) {
          InterestsElement = new global::Common.Entity.V1.InterestsElement();
        }
        InterestsElement.MergeFrom(other.InterestsElement);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (registrationElement_ == null) {
              RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
            }
            input.ReadMessage(RegistrationElement);
            break;
          }
          case 834: {
            if (interestsElement_ == null) {
              InterestsElement = new global::Common.Entity.V1.InterestsElement();
            }
            input.ReadMessage(InterestsElement);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (registrationElement_ == null) {
              RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
            }
            input.ReadMessage(RegistrationElement);
            break;
          }
          case 834: {
            if (interestsElement_ == null) {
              InterestsElement = new global::Common.Entity.V1.InterestsElement();
            }
            input.ReadMessage(InterestsElement);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Entity containing information of a single user that is broadcasted to his/her rosters.
  /// </summary>
  public sealed partial class EntityUserRosterEntry : pb::IMessage<EntityUserRosterEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityUserRosterEntry> _parser = new pb::MessageParser<EntityUserRosterEntry>(() => new EntityUserRosterEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityUserRosterEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUserRosterEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUserRosterEntry(EntityUserRosterEntry other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      emojiStatusElement_ = other.emojiStatusElement_ != null ? other.emojiStatusElement_.Clone() : null;
      username_ = other.username_ != null ? other.username_.Clone() : null;
      displayName_ = other.displayName_ != null ? other.displayName_.Clone() : null;
      profilePic_ = other.profilePic_ != null ? other.profilePic_.Clone() : null;
      botExtension_ = other.botExtension_ != null ? other.botExtension_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityUserRosterEntry Clone() {
      return new EntityUserRosterEntry(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Common.XiBareUserJid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiBareUserJid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "emoji_status_element" field.</summary>
    public const int EmojiStatusElementFieldNumber = 2;
    private global::Common.Entity.V1.EmojiStatusElement emojiStatusElement_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.EmojiStatusElement EmojiStatusElement {
      get { return emojiStatusElement_; }
      set {
        emojiStatusElement_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    private global::Common.Entity.V1.UsernameElement username_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.UsernameElement Username {
      get { return username_; }
      set {
        username_ = value;
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 4;
    private global::Common.Entity.V1.DisplayNameElement displayName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.DisplayNameElement DisplayName {
      get { return displayName_; }
      set {
        displayName_ = value;
      }
    }

    /// <summary>Field number for the "profile_pic" field.</summary>
    public const int ProfilePicFieldNumber = 5;
    private global::Common.Entity.V1.ProfilePicElement profilePic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.ProfilePicElement ProfilePic {
      get { return profilePic_; }
      set {
        profilePic_ = value;
      }
    }

    /// <summary>Field number for the "bot_extension" field.</summary>
    public const int BotExtensionFieldNumber = 6;
    private global::Common.Entity.V1.BotExtensionElement botExtension_;
    /// <summary>
    /// The presence of this element indicates that this User is a bot, regardless of the element's content; Regular Users will never have this element.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BotExtensionElement BotExtension {
      get { return botExtension_; }
      set {
        botExtension_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityUserRosterEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityUserRosterEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(EmojiStatusElement, other.EmojiStatusElement)) return false;
      if (!object.Equals(Username, other.Username)) return false;
      if (!object.Equals(DisplayName, other.DisplayName)) return false;
      if (!object.Equals(ProfilePic, other.ProfilePic)) return false;
      if (!object.Equals(BotExtension, other.BotExtension)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (emojiStatusElement_ != null) hash ^= EmojiStatusElement.GetHashCode();
      if (username_ != null) hash ^= Username.GetHashCode();
      if (displayName_ != null) hash ^= DisplayName.GetHashCode();
      if (profilePic_ != null) hash ^= ProfilePic.GetHashCode();
      if (botExtension_ != null) hash ^= BotExtension.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (emojiStatusElement_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EmojiStatusElement);
      }
      if (username_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Username);
      }
      if (displayName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DisplayName);
      }
      if (profilePic_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ProfilePic);
      }
      if (botExtension_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BotExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (emojiStatusElement_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EmojiStatusElement);
      }
      if (username_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Username);
      }
      if (displayName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DisplayName);
      }
      if (profilePic_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ProfilePic);
      }
      if (botExtension_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BotExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (emojiStatusElement_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmojiStatusElement);
      }
      if (username_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Username);
      }
      if (displayName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DisplayName);
      }
      if (profilePic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProfilePic);
      }
      if (botExtension_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotExtension);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityUserRosterEntry other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Common.XiBareUserJid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.emojiStatusElement_ != null) {
        if (emojiStatusElement_ == null) {
          EmojiStatusElement = new global::Common.Entity.V1.EmojiStatusElement();
        }
        EmojiStatusElement.MergeFrom(other.EmojiStatusElement);
      }
      if (other.username_ != null) {
        if (username_ == null) {
          Username = new global::Common.Entity.V1.UsernameElement();
        }
        Username.MergeFrom(other.Username);
      }
      if (other.displayName_ != null) {
        if (displayName_ == null) {
          DisplayName = new global::Common.Entity.V1.DisplayNameElement();
        }
        DisplayName.MergeFrom(other.DisplayName);
      }
      if (other.profilePic_ != null) {
        if (profilePic_ == null) {
          ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
        }
        ProfilePic.MergeFrom(other.ProfilePic);
      }
      if (other.botExtension_ != null) {
        if (botExtension_ == null) {
          BotExtension = new global::Common.Entity.V1.BotExtensionElement();
        }
        BotExtension.MergeFrom(other.BotExtension);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (emojiStatusElement_ == null) {
              EmojiStatusElement = new global::Common.Entity.V1.EmojiStatusElement();
            }
            input.ReadMessage(EmojiStatusElement);
            break;
          }
          case 26: {
            if (username_ == null) {
              Username = new global::Common.Entity.V1.UsernameElement();
            }
            input.ReadMessage(Username);
            break;
          }
          case 34: {
            if (displayName_ == null) {
              DisplayName = new global::Common.Entity.V1.DisplayNameElement();
            }
            input.ReadMessage(DisplayName);
            break;
          }
          case 42: {
            if (profilePic_ == null) {
              ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
            }
            input.ReadMessage(ProfilePic);
            break;
          }
          case 50: {
            if (botExtension_ == null) {
              BotExtension = new global::Common.Entity.V1.BotExtensionElement();
            }
            input.ReadMessage(BotExtension);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (emojiStatusElement_ == null) {
              EmojiStatusElement = new global::Common.Entity.V1.EmojiStatusElement();
            }
            input.ReadMessage(EmojiStatusElement);
            break;
          }
          case 26: {
            if (username_ == null) {
              Username = new global::Common.Entity.V1.UsernameElement();
            }
            input.ReadMessage(Username);
            break;
          }
          case 34: {
            if (displayName_ == null) {
              DisplayName = new global::Common.Entity.V1.DisplayNameElement();
            }
            input.ReadMessage(DisplayName);
            break;
          }
          case 42: {
            if (profilePic_ == null) {
              ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
            }
            input.ReadMessage(ProfilePic);
            break;
          }
          case 50: {
            if (botExtension_ == null) {
              BotExtension = new global::Common.Entity.V1.BotExtensionElement();
            }
            input.ReadMessage(BotExtension);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Entity containing information of group that is broadcast to its members' rosters.
  /// </summary>
  public sealed partial class EntityGroupRosterEntry : pb::IMessage<EntityGroupRosterEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityGroupRosterEntry> _parser = new pb::MessageParser<EntityGroupRosterEntry>(() => new EntityGroupRosterEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityGroupRosterEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroupRosterEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroupRosterEntry(EntityGroupRosterEntry other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      public_ = other.public_ != null ? other.public_.Clone() : null;
      groupCode_ = other.groupCode_ != null ? other.groupCode_.Clone() : null;
      groupName_ = other.groupName_ != null ? other.groupName_.Clone() : null;
      profilePic_ = other.profilePic_ != null ? other.profilePic_.Clone() : null;
      members_ = other.members_ != null ? other.members_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityGroupRosterEntry Clone() {
      return new EntityGroupRosterEntry(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Common.XiGroupJid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiGroupJid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "public" field.</summary>
    public const int PublicFieldNumber = 2;
    private global::Common.Entity.V1.PublicElement public_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.PublicElement Public {
      get { return public_; }
      set {
        public_ = value;
      }
    }

    /// <summary>Field number for the "group_code" field.</summary>
    public const int GroupCodeFieldNumber = 3;
    private global::Common.Entity.V1.GroupCodeElement groupCode_;
    /// <summary>
    /// Hashtag for the group
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.GroupCodeElement GroupCode {
      get { return groupCode_; }
      set {
        groupCode_ = value;
      }
    }

    /// <summary>Field number for the "group_name" field.</summary>
    public const int GroupNameFieldNumber = 4;
    private global::Common.Entity.V1.GroupNameElement groupName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.GroupNameElement GroupName {
      get { return groupName_; }
      set {
        groupName_ = value;
      }
    }

    /// <summary>Field number for the "profile_pic" field.</summary>
    public const int ProfilePicFieldNumber = 5;
    private global::Common.Entity.V1.ProfilePicElement profilePic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.ProfilePicElement ProfilePic {
      get { return profilePic_; }
      set {
        profilePic_ = value;
      }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 6;
    private global::Common.Entity.V1.GroupMemberListElement members_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.GroupMemberListElement Members {
      get { return members_; }
      set {
        members_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityGroupRosterEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityGroupRosterEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(Public, other.Public)) return false;
      if (!object.Equals(GroupCode, other.GroupCode)) return false;
      if (!object.Equals(GroupName, other.GroupName)) return false;
      if (!object.Equals(ProfilePic, other.ProfilePic)) return false;
      if (!object.Equals(Members, other.Members)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (public_ != null) hash ^= Public.GetHashCode();
      if (groupCode_ != null) hash ^= GroupCode.GetHashCode();
      if (groupName_ != null) hash ^= GroupName.GetHashCode();
      if (profilePic_ != null) hash ^= ProfilePic.GetHashCode();
      if (members_ != null) hash ^= Members.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (public_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Public);
      }
      if (groupCode_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GroupCode);
      }
      if (groupName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GroupName);
      }
      if (profilePic_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ProfilePic);
      }
      if (members_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Members);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (public_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Public);
      }
      if (groupCode_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GroupCode);
      }
      if (groupName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GroupName);
      }
      if (profilePic_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ProfilePic);
      }
      if (members_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Members);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (public_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Public);
      }
      if (groupCode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupCode);
      }
      if (groupName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupName);
      }
      if (profilePic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProfilePic);
      }
      if (members_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Members);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityGroupRosterEntry other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Common.XiGroupJid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.public_ != null) {
        if (public_ == null) {
          Public = new global::Common.Entity.V1.PublicElement();
        }
        Public.MergeFrom(other.Public);
      }
      if (other.groupCode_ != null) {
        if (groupCode_ == null) {
          GroupCode = new global::Common.Entity.V1.GroupCodeElement();
        }
        GroupCode.MergeFrom(other.GroupCode);
      }
      if (other.groupName_ != null) {
        if (groupName_ == null) {
          GroupName = new global::Common.Entity.V1.GroupNameElement();
        }
        GroupName.MergeFrom(other.GroupName);
      }
      if (other.profilePic_ != null) {
        if (profilePic_ == null) {
          ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
        }
        ProfilePic.MergeFrom(other.ProfilePic);
      }
      if (other.members_ != null) {
        if (members_ == null) {
          Members = new global::Common.Entity.V1.GroupMemberListElement();
        }
        Members.MergeFrom(other.Members);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiGroupJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (public_ == null) {
              Public = new global::Common.Entity.V1.PublicElement();
            }
            input.ReadMessage(Public);
            break;
          }
          case 26: {
            if (groupCode_ == null) {
              GroupCode = new global::Common.Entity.V1.GroupCodeElement();
            }
            input.ReadMessage(GroupCode);
            break;
          }
          case 34: {
            if (groupName_ == null) {
              GroupName = new global::Common.Entity.V1.GroupNameElement();
            }
            input.ReadMessage(GroupName);
            break;
          }
          case 42: {
            if (profilePic_ == null) {
              ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
            }
            input.ReadMessage(ProfilePic);
            break;
          }
          case 50: {
            if (members_ == null) {
              Members = new global::Common.Entity.V1.GroupMemberListElement();
            }
            input.ReadMessage(Members);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiGroupJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            if (public_ == null) {
              Public = new global::Common.Entity.V1.PublicElement();
            }
            input.ReadMessage(Public);
            break;
          }
          case 26: {
            if (groupCode_ == null) {
              GroupCode = new global::Common.Entity.V1.GroupCodeElement();
            }
            input.ReadMessage(GroupCode);
            break;
          }
          case 34: {
            if (groupName_ == null) {
              GroupName = new global::Common.Entity.V1.GroupNameElement();
            }
            input.ReadMessage(GroupName);
            break;
          }
          case 42: {
            if (profilePic_ == null) {
              ProfilePic = new global::Common.Entity.V1.ProfilePicElement();
            }
            input.ReadMessage(ProfilePic);
            break;
          }
          case 50: {
            if (members_ == null) {
              Members = new global::Common.Entity.V1.GroupMemberListElement();
            }
            input.ReadMessage(Members);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityBot : pb::IMessage<EntityBot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityBot> _parser = new pb::MessageParser<EntityBot>(() => new EntityBot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityBot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Entity.V1.EntityCommonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityBot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityBot(EntityBot other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      bioElement_ = other.bioElement_ != null ? other.bioElement_.Clone() : null;
      originalProfilePicExtension_ = other.originalProfilePicExtension_ != null ? other.originalProfilePicExtension_.Clone() : null;
      backgroundProfilePicExtension_ = other.backgroundProfilePicExtension_ != null ? other.backgroundProfilePicExtension_.Clone() : null;
      registrationElement_ = other.registrationElement_ != null ? other.registrationElement_.Clone() : null;
      bylineElement_ = other.bylineElement_ != null ? other.bylineElement_.Clone() : null;
      ratingSummary_ = other.ratingSummary_ != null ? other.ratingSummary_.Clone() : null;
      trusted_ = other.trusted_ != null ? other.trusted_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityBot Clone() {
      return new EntityBot(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Common.XiBareUserJid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiBareUserJid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "bio_element" field.</summary>
    public const int BioElementFieldNumber = 100;
    private global::Common.Entity.V1.BioElement bioElement_;
    /// <summary>
    /// Use tag number range of [100-199] for elements sourced from profile service
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BioElement BioElement {
      get { return bioElement_; }
      set {
        bioElement_ = value;
      }
    }

    /// <summary>Field number for the "original_profile_pic_extension" field.</summary>
    public const int OriginalProfilePicExtensionFieldNumber = 101;
    private global::Common.Entity.V1.OriginalProfilePicExtensionElement originalProfilePicExtension_;
    /// <summary>
    /// Original Profile Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.OriginalProfilePicExtensionElement OriginalProfilePicExtension {
      get { return originalProfilePicExtension_; }
      set {
        originalProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "background_profile_pic_extension" field.</summary>
    public const int BackgroundProfilePicExtensionFieldNumber = 102;
    private global::Common.Entity.V1.BackgroundProfilePicExtensionElement backgroundProfilePicExtension_;
    /// <summary>
    /// Background Pic Extension
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BackgroundProfilePicExtensionElement BackgroundProfilePicExtension {
      get { return backgroundProfilePicExtension_; }
      set {
        backgroundProfilePicExtension_ = value;
      }
    }

    /// <summary>Field number for the "registration_element" field.</summary>
    public const int RegistrationElementFieldNumber = 103;
    private global::Common.Entity.V1.RegistrationElement registrationElement_;
    /// <summary>
    /// Registration Element for bot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.RegistrationElement RegistrationElement {
      get { return registrationElement_; }
      set {
        registrationElement_ = value;
      }
    }

    /// <summary>Field number for the "byline_element" field.</summary>
    public const int BylineElementFieldNumber = 200;
    private global::Common.Entity.V1.BylineElement bylineElement_;
    /// <summary>
    /// Byline for a bot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BylineElement BylineElement {
      get { return bylineElement_; }
      set {
        bylineElement_ = value;
      }
    }

    /// <summary>Field number for the "rating_summary" field.</summary>
    public const int RatingSummaryFieldNumber = 201;
    private global::Common.Entity.V1.RatingSummary ratingSummary_;
    /// <summary>
    /// Rating information for the bot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.RatingSummary RatingSummary {
      get { return ratingSummary_; }
      set {
        ratingSummary_ = value;
      }
    }

    /// <summary>Field number for the "trusted" field.</summary>
    public const int TrustedFieldNumber = 202;
    private global::Common.Entity.V1.TrustedElement trusted_;
    /// <summary>
    /// Is the bot trusted
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.TrustedElement Trusted {
      get { return trusted_; }
      set {
        trusted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityBot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityBot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(BioElement, other.BioElement)) return false;
      if (!object.Equals(OriginalProfilePicExtension, other.OriginalProfilePicExtension)) return false;
      if (!object.Equals(BackgroundProfilePicExtension, other.BackgroundProfilePicExtension)) return false;
      if (!object.Equals(RegistrationElement, other.RegistrationElement)) return false;
      if (!object.Equals(BylineElement, other.BylineElement)) return false;
      if (!object.Equals(RatingSummary, other.RatingSummary)) return false;
      if (!object.Equals(Trusted, other.Trusted)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (bioElement_ != null) hash ^= BioElement.GetHashCode();
      if (originalProfilePicExtension_ != null) hash ^= OriginalProfilePicExtension.GetHashCode();
      if (backgroundProfilePicExtension_ != null) hash ^= BackgroundProfilePicExtension.GetHashCode();
      if (registrationElement_ != null) hash ^= RegistrationElement.GetHashCode();
      if (bylineElement_ != null) hash ^= BylineElement.GetHashCode();
      if (ratingSummary_ != null) hash ^= RatingSummary.GetHashCode();
      if (trusted_ != null) hash ^= Trusted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(RegistrationElement);
      }
      if (bylineElement_ != null) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(BylineElement);
      }
      if (ratingSummary_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(RatingSummary);
      }
      if (trusted_ != null) {
        output.WriteRawTag(210, 12);
        output.WriteMessage(Trusted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (bioElement_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(RegistrationElement);
      }
      if (bylineElement_ != null) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(BylineElement);
      }
      if (ratingSummary_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(RatingSummary);
      }
      if (trusted_ != null) {
        output.WriteRawTag(210, 12);
        output.WriteMessage(Trusted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (bioElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BioElement);
      }
      if (originalProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OriginalProfilePicExtension);
      }
      if (backgroundProfilePicExtension_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BackgroundProfilePicExtension);
      }
      if (registrationElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RegistrationElement);
      }
      if (bylineElement_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BylineElement);
      }
      if (ratingSummary_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RatingSummary);
      }
      if (trusted_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Trusted);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityBot other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Common.XiBareUserJid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.bioElement_ != null) {
        if (bioElement_ == null) {
          BioElement = new global::Common.Entity.V1.BioElement();
        }
        BioElement.MergeFrom(other.BioElement);
      }
      if (other.originalProfilePicExtension_ != null) {
        if (originalProfilePicExtension_ == null) {
          OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
        }
        OriginalProfilePicExtension.MergeFrom(other.OriginalProfilePicExtension);
      }
      if (other.backgroundProfilePicExtension_ != null) {
        if (backgroundProfilePicExtension_ == null) {
          BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
        }
        BackgroundProfilePicExtension.MergeFrom(other.BackgroundProfilePicExtension);
      }
      if (other.registrationElement_ != null) {
        if (registrationElement_ == null) {
          RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
        }
        RegistrationElement.MergeFrom(other.RegistrationElement);
      }
      if (other.bylineElement_ != null) {
        if (bylineElement_ == null) {
          BylineElement = new global::Common.Entity.V1.BylineElement();
        }
        BylineElement.MergeFrom(other.BylineElement);
      }
      if (other.ratingSummary_ != null) {
        if (ratingSummary_ == null) {
          RatingSummary = new global::Common.Entity.V1.RatingSummary();
        }
        RatingSummary.MergeFrom(other.RatingSummary);
      }
      if (other.trusted_ != null) {
        if (trusted_ == null) {
          Trusted = new global::Common.Entity.V1.TrustedElement();
        }
        Trusted.MergeFrom(other.Trusted);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (registrationElement_ == null) {
              RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
            }
            input.ReadMessage(RegistrationElement);
            break;
          }
          case 1602: {
            if (bylineElement_ == null) {
              BylineElement = new global::Common.Entity.V1.BylineElement();
            }
            input.ReadMessage(BylineElement);
            break;
          }
          case 1610: {
            if (ratingSummary_ == null) {
              RatingSummary = new global::Common.Entity.V1.RatingSummary();
            }
            input.ReadMessage(RatingSummary);
            break;
          }
          case 1618: {
            if (trusted_ == null) {
              Trusted = new global::Common.Entity.V1.TrustedElement();
            }
            input.ReadMessage(Trusted);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(Id);
            break;
          }
          case 802: {
            if (bioElement_ == null) {
              BioElement = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(BioElement);
            break;
          }
          case 810: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
          case 818: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
          case 826: {
            if (registrationElement_ == null) {
              RegistrationElement = new global::Common.Entity.V1.RegistrationElement();
            }
            input.ReadMessage(RegistrationElement);
            break;
          }
          case 1602: {
            if (bylineElement_ == null) {
              BylineElement = new global::Common.Entity.V1.BylineElement();
            }
            input.ReadMessage(BylineElement);
            break;
          }
          case 1610: {
            if (ratingSummary_ == null) {
              RatingSummary = new global::Common.Entity.V1.RatingSummary();
            }
            input.ReadMessage(RatingSummary);
            break;
          }
          case 1618: {
            if (trusted_ == null) {
              Trusted = new global::Common.Entity.V1.TrustedElement();
            }
            input.ReadMessage(Trusted);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
