// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: group_suggest_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mobile.Groups.V1 {

  /// <summary>Holder for reflection information generated from group_suggest_service.proto</summary>
  public static partial class GroupSuggestServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for group_suggest_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GroupSuggestServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtncm91cF9zdWdnZXN0X3NlcnZpY2UucHJvdG8SEG1vYmlsZS5ncm91cHMu",
            "djEaGXByb3RvYnVmX3ZhbGlkYXRpb24ucHJvdG8iJQojR2V0U3VnZ2VzdGVk",
            "R3JvdXBTZWFyY2hUZXJtc1JlcXVlc3QixwIKJEdldFN1Z2dlc3RlZEdyb3Vw",
            "U2VhcmNoVGVybXNSZXNwb25zZRJNCgZyZXN1bHQYASABKA4yPS5tb2JpbGUu",
            "Z3JvdXBzLnYxLkdldFN1Z2dlc3RlZEdyb3VwU2VhcmNoVGVybXNSZXNwb25z",
            "ZS5SZXN1bHQSZwoOc3VnZ2VzdGVkX3Rlcm0YAiADKAsyRC5tb2JpbGUuZ3Jv",
            "dXBzLnYxLkdldFN1Z2dlc3RlZEdyb3VwU2VhcmNoVGVybXNSZXNwb25zZS5T",
            "dWdnZXN0ZWRUZXJtQgnKnSUFCACAAWQaPAoNU3VnZ2VzdGVkVGVybRIrCgR0",
            "ZXJtGAEgASgJQh3KnSUZCAESFV5bQS1aYS16MC05Ll9dezEsMzJ9JCIpCgZS",
            "ZXN1bHQSBgoCT0sQABIXChNSQVRFX0xJTUlUX0VYQ0VFREVEEAEyoAEKDEdy",
            "b3VwU3VnZ2VzdBKPAQocR2V0U3VnZ2VzdGVkR3JvdXBTZWFyY2hUZXJtcxI1",
            "Lm1vYmlsZS5ncm91cHMudjEuR2V0U3VnZ2VzdGVkR3JvdXBTZWFyY2hUZXJt",
            "c1JlcXVlc3QaNi5tb2JpbGUuZ3JvdXBzLnYxLkdldFN1Z2dlc3RlZEdyb3Vw",
            "U2VhcmNoVGVybXNSZXNwb25zZSIAQlwKDmNvbS5raWsuZ3JvdXBzWkpnaXRo",
            "dWIuY29tL2tpa2ludGVyYWN0aXZlL3hpcGhpYXMtYXBpLW1vYmlsZS9nZW5l",
            "cmF0ZWQvZ28vZ3JvdXBzL3YxO2dyb3Vwc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kik.Validation.ProtobufValidationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsRequest), global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse), global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Parser, new[]{ "Result", "SuggestedTerm" }, null, new[]{ typeof(global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm), global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm.Parser, new[]{ "Term" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetSuggestedGroupSearchTermsRequest : pb::IMessage<GetSuggestedGroupSearchTermsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSuggestedGroupSearchTermsRequest> _parser = new pb::MessageParser<GetSuggestedGroupSearchTermsRequest>(() => new GetSuggestedGroupSearchTermsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetSuggestedGroupSearchTermsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mobile.Groups.V1.GroupSuggestServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsRequest(GetSuggestedGroupSearchTermsRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsRequest Clone() {
      return new GetSuggestedGroupSearchTermsRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetSuggestedGroupSearchTermsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetSuggestedGroupSearchTermsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetSuggestedGroupSearchTermsRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class GetSuggestedGroupSearchTermsResponse : pb::IMessage<GetSuggestedGroupSearchTermsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSuggestedGroupSearchTermsResponse> _parser = new pb::MessageParser<GetSuggestedGroupSearchTermsResponse>(() => new GetSuggestedGroupSearchTermsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetSuggestedGroupSearchTermsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mobile.Groups.V1.GroupSuggestServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsResponse(GetSuggestedGroupSearchTermsResponse other) : this() {
      result_ = other.result_;
      suggestedTerm_ = other.suggestedTerm_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSuggestedGroupSearchTermsResponse Clone() {
      return new GetSuggestedGroupSearchTermsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result result_ = global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "suggested_term" field.</summary>
    public const int SuggestedTermFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm> _repeated_suggestedTerm_codec
        = pb::FieldCodec.ForMessage(18, global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm.Parser);
    private readonly pbc::RepeatedField<global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm> suggestedTerm_ = new pbc::RepeatedField<global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.SuggestedTerm> SuggestedTerm {
      get { return suggestedTerm_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetSuggestedGroupSearchTermsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetSuggestedGroupSearchTermsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!suggestedTerm_.Equals(other.suggestedTerm_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok) hash ^= Result.GetHashCode();
      hash ^= suggestedTerm_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      suggestedTerm_.WriteTo(output, _repeated_suggestedTerm_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      suggestedTerm_.WriteTo(ref output, _repeated_suggestedTerm_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += suggestedTerm_.CalculateSize(_repeated_suggestedTerm_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetSuggestedGroupSearchTermsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result.Ok) {
        Result = other.Result;
      }
      suggestedTerm_.Add(other.suggestedTerm_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            suggestedTerm_.AddEntriesFrom(input, _repeated_suggestedTerm_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            suggestedTerm_.AddEntriesFrom(ref input, _repeated_suggestedTerm_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GetSuggestedGroupSearchTermsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("RATE_LIMIT_EXCEEDED")] RateLimitExceeded = 1,
      }

      public sealed partial class SuggestedTerm : pb::IMessage<SuggestedTerm>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SuggestedTerm> _parser = new pb::MessageParser<SuggestedTerm>(() => new SuggestedTerm());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<SuggestedTerm> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mobile.Groups.V1.GetSuggestedGroupSearchTermsResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public SuggestedTerm() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public SuggestedTerm(SuggestedTerm other) : this() {
          term_ = other.term_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public SuggestedTerm Clone() {
          return new SuggestedTerm(this);
        }

        /// <summary>Field number for the "term" field.</summary>
        public const int TermFieldNumber = 1;
        private string term_ = "";
        /// <summary>
        /// A simple string intended as a search term that may be presented to
        /// the user as a suggestion to use when searching for groups.  If
        /// selected, this term should be provided to the group search service
        /// as-is.
        /// Note these terms will not have a '#' character prefix, nor any special
        /// wildcards. (there are no wildcards included in the spec at this time)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Term {
          get { return term_; }
          set {
            term_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as SuggestedTerm);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(SuggestedTerm other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Term != other.Term) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Term.Length != 0) hash ^= Term.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Term.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Term);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Term.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Term);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Term.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Term);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(SuggestedTerm other) {
          if (other == null) {
            return;
          }
          if (other.Term.Length != 0) {
            Term = other.Term;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Term = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Term = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
