// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messagepath/v1/mentions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Messagepath.V1 {

  /// <summary>Holder for reflection information generated from messagepath/v1/mentions.proto</summary>
  public static partial class MentionsReflection {

    #region Descriptor
    /// <summary>File descriptor for messagepath/v1/mentions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MentionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1tZXNzYWdlcGF0aC92MS9tZW50aW9ucy5wcm90bxIVY29tbW9uLm1lc3Nh",
            "Z2VwYXRoLnYxGhJjb21tb25fbW9kZWwucHJvdG8aGXByb3RvYnVmX3ZhbGlk",
            "YXRpb24ucHJvdG8iSwoWTWVudGlvblJlcGx5QXR0YWNobWVudBIxChJvcmln",
            "aW5hbF9tZW50aW9uZXIYASABKAsyFS5jb21tb24uWGlCYXJlVXNlckppZEJ3",
            "Chljb20ua2lrLm1lc3NhZ2VwYXRoLm1vZGVsWlNnaXRodWIuY29tL2tpa2lu",
            "dGVyYWN0aXZlL3hpcGhpYXMtbW9kZWwtY29tbW9uL2dlbmVyYXRlZC9nby9t",
            "ZXNzYWdlcGF0aDttZXNzYWdlcGF0aKICBE1QVEhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonModelReflection.Descriptor, global::Kik.Validation.ProtobufValidationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Messagepath.V1.MentionReplyAttachment), global::Common.Messagepath.V1.MentionReplyAttachment.Parser, new[]{ "OriginalMentioner" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// For mention replies (from bots to users), this attachment is used to indicate the user who
  /// originally mentioned the bot.
  ///
  /// See https://github.com/kikinteractive/kik-product/wiki/Bot-Mentions
  ///
  /// This should only be used the client for internal logic specific to mention-reply messages
  /// (e.g. on iPhone 10.9 it is used to determine whether to show the "Reply" button)
  /// DO NOT use this attachment to determine visibility rules (use the visibility_rules_attachment for that).
  /// </summary>
  public sealed partial class MentionReplyAttachment : pb::IMessage<MentionReplyAttachment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MentionReplyAttachment> _parser = new pb::MessageParser<MentionReplyAttachment>(() => new MentionReplyAttachment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MentionReplyAttachment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Messagepath.V1.MentionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MentionReplyAttachment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MentionReplyAttachment(MentionReplyAttachment other) : this() {
      originalMentioner_ = other.originalMentioner_ != null ? other.originalMentioner_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MentionReplyAttachment Clone() {
      return new MentionReplyAttachment(this);
    }

    /// <summary>Field number for the "original_mentioner" field.</summary>
    public const int OriginalMentionerFieldNumber = 1;
    private global::Common.XiBareUserJid originalMentioner_;
    /// <summary>
    /// The original user who mentioned the bot.
    /// Field is OPTIONAL but should be set when the mentioner is known.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.XiBareUserJid OriginalMentioner {
      get { return originalMentioner_; }
      set {
        originalMentioner_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MentionReplyAttachment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MentionReplyAttachment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OriginalMentioner, other.OriginalMentioner)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (originalMentioner_ != null) hash ^= OriginalMentioner.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (originalMentioner_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriginalMentioner);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (originalMentioner_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriginalMentioner);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (originalMentioner_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriginalMentioner);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MentionReplyAttachment other) {
      if (other == null) {
        return;
      }
      if (other.originalMentioner_ != null) {
        if (originalMentioner_ == null) {
          OriginalMentioner = new global::Common.XiBareUserJid();
        }
        OriginalMentioner.MergeFrom(other.OriginalMentioner);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (originalMentioner_ == null) {
              OriginalMentioner = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(OriginalMentioner);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (originalMentioner_ == null) {
              OriginalMentioner = new global::Common.XiBareUserJid();
            }
            input.ReadMessage(OriginalMentioner);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
