// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mobile_video_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mobileremote.Video.V1 {

  /// <summary>Holder for reflection information generated from mobile_video_service.proto</summary>
  public static partial class MobileVideoServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for mobile_video_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MobileVideoServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chptb2JpbGVfdmlkZW9fc2VydmljZS5wcm90bxIVbW9iaWxlcmVtb3RlLnZp",
            "ZGVvLnYxGhlwcm90b2J1Zl92YWxpZGF0aW9uLnByb3RvGhJjb21tb25fbW9k",
            "ZWwucHJvdG8aEGNvbW1vbl9ycGMucHJvdG8aG3ZpZGVvL3YxL3ZpZGVvX2Nv",
            "bW1vbi5wcm90byKEAQokT25Db252b1ZpZGVvU3RhdGVDaGFuZ2VkTm90aWZp",
            "Y2F0aW9uEjsKEWNvbnZvX3ZpZGVvX3N0YXRlGAEgASgLMiAuY29tbW9uLnZp",
            "ZGVvLnYxLkNvbnZvVmlkZW9TdGF0ZRIfCg9ub3RpZmljYXRpb25faWQYAiAB",
            "KAlCBsqdJQIwJDJ8CgtNb2JpbGVWaWRlbxJtChhPbkNvbnZvVmlkZW9TdGF0",
            "ZUNoYW5nZWQSOy5tb2JpbGVyZW1vdGUudmlkZW8udjEuT25Db252b1ZpZGVv",
            "U3RhdGVDaGFuZ2VkTm90aWZpY2F0aW9uGhQuY29tbW9uLlZvaWRSZXNwb25z",
            "ZUJsChpjb20ua2lrLnZpZGVvLm1vYmlsZXJlbW90ZVpOZ2l0aHViLmNvbS9r",
            "aWtpbnRlcmFjdGl2ZS94aXBoaWFzLWFwaS1tb2JpbGVyZW1vdGUvZ2VuZXJh",
            "dGVkL2dvL3ZpZGVvL3YxO3ZpZGVvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kik.Validation.ProtobufValidationReflection.Descriptor, global::Common.CommonModelReflection.Descriptor, global::Common.CommonRpcReflection.Descriptor, global::Common.Video.V1.VideoCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mobileremote.Video.V1.OnConvoVideoStateChangedNotification), global::Mobileremote.Video.V1.OnConvoVideoStateChangedNotification.Parser, new[]{ "ConvoVideoState", "NotificationId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OnConvoVideoStateChangedNotification : pb::IMessage<OnConvoVideoStateChangedNotification>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnConvoVideoStateChangedNotification> _parser = new pb::MessageParser<OnConvoVideoStateChangedNotification>(() => new OnConvoVideoStateChangedNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OnConvoVideoStateChangedNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mobileremote.Video.V1.MobileVideoServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OnConvoVideoStateChangedNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OnConvoVideoStateChangedNotification(OnConvoVideoStateChangedNotification other) : this() {
      convoVideoState_ = other.convoVideoState_ != null ? other.convoVideoState_.Clone() : null;
      notificationId_ = other.notificationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OnConvoVideoStateChangedNotification Clone() {
      return new OnConvoVideoStateChangedNotification(this);
    }

    /// <summary>Field number for the "convo_video_state" field.</summary>
    public const int ConvoVideoStateFieldNumber = 1;
    private global::Common.Video.V1.ConvoVideoState convoVideoState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Video.V1.ConvoVideoState ConvoVideoState {
      get { return convoVideoState_; }
      set {
        convoVideoState_ = value;
      }
    }

    /// <summary>Field number for the "notification_id" field.</summary>
    public const int NotificationIdFieldNumber = 2;
    private string notificationId_ = "";
    /// <summary>
    /// Uniquely identifies a push notification of a state change. This is used to relate a
    /// push harpy event (sent from InternalKikVideoService) and the client push ack'd harpy event.
    ///
    /// Consumers of this service should _not_ make any assumptions about the underlying data
    /// format of the notification_id.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NotificationId {
      get { return notificationId_; }
      set {
        notificationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OnConvoVideoStateChangedNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OnConvoVideoStateChangedNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ConvoVideoState, other.ConvoVideoState)) return false;
      if (NotificationId != other.NotificationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (convoVideoState_ != null) hash ^= ConvoVideoState.GetHashCode();
      if (NotificationId.Length != 0) hash ^= NotificationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (convoVideoState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConvoVideoState);
      }
      if (NotificationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NotificationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (convoVideoState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConvoVideoState);
      }
      if (NotificationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NotificationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (convoVideoState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConvoVideoState);
      }
      if (NotificationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NotificationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OnConvoVideoStateChangedNotification other) {
      if (other == null) {
        return;
      }
      if (other.convoVideoState_ != null) {
        if (convoVideoState_ == null) {
          ConvoVideoState = new global::Common.Video.V1.ConvoVideoState();
        }
        ConvoVideoState.MergeFrom(other.ConvoVideoState);
      }
      if (other.NotificationId.Length != 0) {
        NotificationId = other.NotificationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (convoVideoState_ == null) {
              ConvoVideoState = new global::Common.Video.V1.ConvoVideoState();
            }
            input.ReadMessage(ConvoVideoState);
            break;
          }
          case 18: {
            NotificationId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (convoVideoState_ == null) {
              ConvoVideoState = new global::Common.Video.V1.ConvoVideoState();
            }
            input.ReadMessage(ConvoVideoState);
            break;
          }
          case 18: {
            NotificationId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
