// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: profile/v1/profile_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Profile.V1 {

  /// <summary>Holder for reflection information generated from profile/v1/profile_common.proto</summary>
  public static partial class ProfileCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for profile/v1/profile_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9wcm9maWxlL3YxL3Byb2ZpbGVfY29tbW9uLnByb3RvEhFjb21tb24ucHJv",
            "ZmlsZS52MRoeZW50aXR5L3YxL2VsZW1lbnRfY29tbW9uLnByb3RvIpIBCglC",
            "aW9BY3Rpb24SNgoLYWN0aW9uX3R5cGUYASABKA4yIS5jb21tb24ucHJvZmls",
            "ZS52MS5CaW9BY3Rpb24uVHlwZRIxCgtlbGVtZW50X2JpbxgCIAEoCzIcLmNv",
            "bW1vbi5lbnRpdHkudjEuQmlvRWxlbWVudCIaCgRUeXBlEgcKA1NFVBAAEgkK",
            "BVVOU0VUEAEi7QEKIU9yaWdpbmFsUHJvZmlsZVBpY0V4dGVuc2lvbkFjdGlv",
            "bhJOCgthY3Rpb25fdHlwZRgBIAEoDjI5LmNvbW1vbi5wcm9maWxlLnYxLk9y",
            "aWdpbmFsUHJvZmlsZVBpY0V4dGVuc2lvbkFjdGlvbi5UeXBlElwKHm9yaWdp",
            "bmFsX3Byb2ZpbGVfcGljX2V4dGVuc2lvbhgCIAEoCzI0LmNvbW1vbi5lbnRp",
            "dHkudjEuT3JpZ2luYWxQcm9maWxlUGljRXh0ZW5zaW9uRWxlbWVudCIaCgRU",
            "eXBlEgcKA1NFVBAAEgkKBVVOU0VUEAEi9QEKI0JhY2tncm91bmRQcm9maWxl",
            "UGljRXh0ZW5zaW9uQWN0aW9uElAKC2FjdGlvbl90eXBlGAEgASgOMjsuY29t",
            "bW9uLnByb2ZpbGUudjEuQmFja2dyb3VuZFByb2ZpbGVQaWNFeHRlbnNpb25B",
            "Y3Rpb24uVHlwZRJgCiBiYWNrZ3JvdW5kX3Byb2ZpbGVfcGljX2V4dGVuc2lv",
            "bhgCIAEoCzI2LmNvbW1vbi5lbnRpdHkudjEuQmFja2dyb3VuZFByb2ZpbGVQ",
            "aWNFeHRlbnNpb25FbGVtZW50IhoKBFR5cGUSBwoDU0VUEAASCQoFVU5TRVQQ",
            "ASKzAQoRRW1vamlTdGF0dXNBY3Rpb24SPgoLYWN0aW9uX3R5cGUYASABKA4y",
            "KS5jb21tb24ucHJvZmlsZS52MS5FbW9qaVN0YXR1c0FjdGlvbi5UeXBlEkIK",
            "FGVsZW1lbnRfZW1vamlfc3RhdHVzGAIgASgLMiQuY29tbW9uLmVudGl0eS52",
            "MS5FbW9qaVN0YXR1c0VsZW1lbnQiGgoEVHlwZRIHCgNTRVQQABIJCgVVTlNF",
            "VBABIqIBCg9JbnRlcmVzdHNBY3Rpb24SPAoLYWN0aW9uX3R5cGUYASABKA4y",
            "Jy5jb21tb24ucHJvZmlsZS52MS5JbnRlcmVzdHNBY3Rpb24uVHlwZRI1Cglp",
            "bnRlcmVzdHMYAiABKAsyIi5jb21tb24uZW50aXR5LnYxLkludGVyZXN0c0Vs",
            "ZW1lbnQiGgoEVHlwZRIHCgNTRVQQABIJCgVVTlNFVBABQmEKD2NvbS5raWsu",
            "cHJvZmlsZVpOZ2l0aHViLmNvbS9raWtpbnRlcmFjdGl2ZS94aXBoaWFzLW1v",
            "ZGVsLWNvbW1vbi9nZW5lcmF0ZWQvZ28vcHJvZmlsZS92MTtwcm9maWxlYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.Entity.V1.ElementCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Profile.V1.BioAction), global::Common.Profile.V1.BioAction.Parser, new[]{ "ActionType", "ElementBio" }, null, new[]{ typeof(global::Common.Profile.V1.BioAction.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Profile.V1.OriginalProfilePicExtensionAction), global::Common.Profile.V1.OriginalProfilePicExtensionAction.Parser, new[]{ "ActionType", "OriginalProfilePicExtension" }, null, new[]{ typeof(global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Profile.V1.BackgroundProfilePicExtensionAction), global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Parser, new[]{ "ActionType", "BackgroundProfilePicExtension" }, null, new[]{ typeof(global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Profile.V1.EmojiStatusAction), global::Common.Profile.V1.EmojiStatusAction.Parser, new[]{ "ActionType", "ElementEmojiStatus" }, null, new[]{ typeof(global::Common.Profile.V1.EmojiStatusAction.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Profile.V1.InterestsAction), global::Common.Profile.V1.InterestsAction.Parser, new[]{ "ActionType", "Interests" }, null, new[]{ typeof(global::Common.Profile.V1.InterestsAction.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// User/Group bio
  /// </summary>
  public sealed partial class BioAction : pb::IMessage<BioAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BioAction> _parser = new pb::MessageParser<BioAction>(() => new BioAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BioAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Profile.V1.ProfileCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BioAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BioAction(BioAction other) : this() {
      actionType_ = other.actionType_;
      elementBio_ = other.elementBio_ != null ? other.elementBio_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BioAction Clone() {
      return new BioAction(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Common.Profile.V1.BioAction.Types.Type actionType_ = global::Common.Profile.V1.BioAction.Types.Type.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Profile.V1.BioAction.Types.Type ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "element_bio" field.</summary>
    public const int ElementBioFieldNumber = 2;
    private global::Common.Entity.V1.BioElement elementBio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BioElement ElementBio {
      get { return elementBio_; }
      set {
        elementBio_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BioAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BioAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (!object.Equals(ElementBio, other.ElementBio)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Common.Profile.V1.BioAction.Types.Type.Set) hash ^= ActionType.GetHashCode();
      if (elementBio_ != null) hash ^= ElementBio.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Common.Profile.V1.BioAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (elementBio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementBio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Common.Profile.V1.BioAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (elementBio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementBio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Common.Profile.V1.BioAction.Types.Type.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (elementBio_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementBio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BioAction other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Common.Profile.V1.BioAction.Types.Type.Set) {
        ActionType = other.ActionType;
      }
      if (other.elementBio_ != null) {
        if (elementBio_ == null) {
          ElementBio = new global::Common.Entity.V1.BioElement();
        }
        ElementBio.MergeFrom(other.ElementBio);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.BioAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (elementBio_ == null) {
              ElementBio = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(ElementBio);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.BioAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (elementBio_ == null) {
              ElementBio = new global::Common.Entity.V1.BioElement();
            }
            input.ReadMessage(ElementBio);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BioAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("SET")] Set = 0,
        [pbr::OriginalName("UNSET")] Unset = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// Original Profile Pic Extension
  /// </summary>
  public sealed partial class OriginalProfilePicExtensionAction : pb::IMessage<OriginalProfilePicExtensionAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OriginalProfilePicExtensionAction> _parser = new pb::MessageParser<OriginalProfilePicExtensionAction>(() => new OriginalProfilePicExtensionAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OriginalProfilePicExtensionAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Profile.V1.ProfileCommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OriginalProfilePicExtensionAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OriginalProfilePicExtensionAction(OriginalProfilePicExtensionAction other) : this() {
      actionType_ = other.actionType_;
      originalProfilePicExtension_ = other.originalProfilePicExtension_ != null ? other.originalProfilePicExtension_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OriginalProfilePicExtensionAction Clone() {
      return new OriginalProfilePicExtensionAction(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type actionType_ = global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "original_profile_pic_extension" field.</summary>
    public const int OriginalProfilePicExtensionFieldNumber = 2;
    private global::Common.Entity.V1.OriginalProfilePicExtensionElement originalProfilePicExtension_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.OriginalProfilePicExtensionElement OriginalProfilePicExtension {
      get { return originalProfilePicExtension_; }
      set {
        originalProfilePicExtension_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OriginalProfilePicExtensionAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OriginalProfilePicExtensionAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (!object.Equals(OriginalProfilePicExtension, other.OriginalProfilePicExtension)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set) hash ^= ActionType.GetHashCode();
      if (originalProfilePicExtension_ != null) hash ^= OriginalProfilePicExtension.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (originalProfilePicExtension_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OriginalProfilePicExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (originalProfilePicExtension_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriginalProfilePicExtension);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OriginalProfilePicExtensionAction other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type.Set) {
        ActionType = other.ActionType;
      }
      if (other.originalProfilePicExtension_ != null) {
        if (originalProfilePicExtension_ == null) {
          OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
        }
        OriginalProfilePicExtension.MergeFrom(other.OriginalProfilePicExtension);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.OriginalProfilePicExtensionAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (originalProfilePicExtension_ == null) {
              OriginalProfilePicExtension = new global::Common.Entity.V1.OriginalProfilePicExtensionElement();
            }
            input.ReadMessage(OriginalProfilePicExtension);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OriginalProfilePicExtensionAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("SET")] Set = 0,
        [pbr::OriginalName("UNSET")] Unset = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// Background Pic Extension
  /// </summary>
  public sealed partial class BackgroundProfilePicExtensionAction : pb::IMessage<BackgroundProfilePicExtensionAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BackgroundProfilePicExtensionAction> _parser = new pb::MessageParser<BackgroundProfilePicExtensionAction>(() => new BackgroundProfilePicExtensionAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BackgroundProfilePicExtensionAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Profile.V1.ProfileCommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BackgroundProfilePicExtensionAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BackgroundProfilePicExtensionAction(BackgroundProfilePicExtensionAction other) : this() {
      actionType_ = other.actionType_;
      backgroundProfilePicExtension_ = other.backgroundProfilePicExtension_ != null ? other.backgroundProfilePicExtension_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BackgroundProfilePicExtensionAction Clone() {
      return new BackgroundProfilePicExtensionAction(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type actionType_ = global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "background_profile_pic_extension" field.</summary>
    public const int BackgroundProfilePicExtensionFieldNumber = 2;
    private global::Common.Entity.V1.BackgroundProfilePicExtensionElement backgroundProfilePicExtension_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.BackgroundProfilePicExtensionElement BackgroundProfilePicExtension {
      get { return backgroundProfilePicExtension_; }
      set {
        backgroundProfilePicExtension_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BackgroundProfilePicExtensionAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BackgroundProfilePicExtensionAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (!object.Equals(BackgroundProfilePicExtension, other.BackgroundProfilePicExtension)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set) hash ^= ActionType.GetHashCode();
      if (backgroundProfilePicExtension_ != null) hash ^= BackgroundProfilePicExtension.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (backgroundProfilePicExtension_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BackgroundProfilePicExtension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (backgroundProfilePicExtension_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BackgroundProfilePicExtension);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BackgroundProfilePicExtensionAction other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type.Set) {
        ActionType = other.ActionType;
      }
      if (other.backgroundProfilePicExtension_ != null) {
        if (backgroundProfilePicExtension_ == null) {
          BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
        }
        BackgroundProfilePicExtension.MergeFrom(other.BackgroundProfilePicExtension);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.BackgroundProfilePicExtensionAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (backgroundProfilePicExtension_ == null) {
              BackgroundProfilePicExtension = new global::Common.Entity.V1.BackgroundProfilePicExtensionElement();
            }
            input.ReadMessage(BackgroundProfilePicExtension);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BackgroundProfilePicExtensionAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("SET")] Set = 0,
        [pbr::OriginalName("UNSET")] Unset = 1,
      }

    }
    #endregion

  }

  public sealed partial class EmojiStatusAction : pb::IMessage<EmojiStatusAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmojiStatusAction> _parser = new pb::MessageParser<EmojiStatusAction>(() => new EmojiStatusAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmojiStatusAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Profile.V1.ProfileCommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmojiStatusAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmojiStatusAction(EmojiStatusAction other) : this() {
      actionType_ = other.actionType_;
      elementEmojiStatus_ = other.elementEmojiStatus_ != null ? other.elementEmojiStatus_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmojiStatusAction Clone() {
      return new EmojiStatusAction(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Common.Profile.V1.EmojiStatusAction.Types.Type actionType_ = global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Profile.V1.EmojiStatusAction.Types.Type ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "element_emoji_status" field.</summary>
    public const int ElementEmojiStatusFieldNumber = 2;
    private global::Common.Entity.V1.EmojiStatusElement elementEmojiStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.EmojiStatusElement ElementEmojiStatus {
      get { return elementEmojiStatus_; }
      set {
        elementEmojiStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmojiStatusAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmojiStatusAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (!object.Equals(ElementEmojiStatus, other.ElementEmojiStatus)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set) hash ^= ActionType.GetHashCode();
      if (elementEmojiStatus_ != null) hash ^= ElementEmojiStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (elementEmojiStatus_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementEmojiStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (elementEmojiStatus_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementEmojiStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (elementEmojiStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementEmojiStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmojiStatusAction other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Common.Profile.V1.EmojiStatusAction.Types.Type.Set) {
        ActionType = other.ActionType;
      }
      if (other.elementEmojiStatus_ != null) {
        if (elementEmojiStatus_ == null) {
          ElementEmojiStatus = new global::Common.Entity.V1.EmojiStatusElement();
        }
        ElementEmojiStatus.MergeFrom(other.ElementEmojiStatus);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.EmojiStatusAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (elementEmojiStatus_ == null) {
              ElementEmojiStatus = new global::Common.Entity.V1.EmojiStatusElement();
            }
            input.ReadMessage(ElementEmojiStatus);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.EmojiStatusAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (elementEmojiStatus_ == null) {
              ElementEmojiStatus = new global::Common.Entity.V1.EmojiStatusElement();
            }
            input.ReadMessage(ElementEmojiStatus);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EmojiStatusAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("SET")] Set = 0,
        [pbr::OriginalName("UNSET")] Unset = 1,
      }

    }
    #endregion

  }

  public sealed partial class InterestsAction : pb::IMessage<InterestsAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InterestsAction> _parser = new pb::MessageParser<InterestsAction>(() => new InterestsAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InterestsAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Profile.V1.ProfileCommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterestsAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterestsAction(InterestsAction other) : this() {
      actionType_ = other.actionType_;
      interests_ = other.interests_ != null ? other.interests_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterestsAction Clone() {
      return new InterestsAction(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Common.Profile.V1.InterestsAction.Types.Type actionType_ = global::Common.Profile.V1.InterestsAction.Types.Type.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Profile.V1.InterestsAction.Types.Type ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "interests" field.</summary>
    public const int InterestsFieldNumber = 2;
    private global::Common.Entity.V1.InterestsElement interests_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.InterestsElement Interests {
      get { return interests_; }
      set {
        interests_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InterestsAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InterestsAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (!object.Equals(Interests, other.Interests)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Common.Profile.V1.InterestsAction.Types.Type.Set) hash ^= ActionType.GetHashCode();
      if (interests_ != null) hash ^= Interests.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Common.Profile.V1.InterestsAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (interests_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Interests);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Common.Profile.V1.InterestsAction.Types.Type.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      if (interests_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Interests);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Common.Profile.V1.InterestsAction.Types.Type.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (interests_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Interests);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InterestsAction other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Common.Profile.V1.InterestsAction.Types.Type.Set) {
        ActionType = other.ActionType;
      }
      if (other.interests_ != null) {
        if (interests_ == null) {
          Interests = new global::Common.Entity.V1.InterestsElement();
        }
        Interests.MergeFrom(other.Interests);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.InterestsAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (interests_ == null) {
              Interests = new global::Common.Entity.V1.InterestsElement();
            }
            input.ReadMessage(Interests);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Common.Profile.V1.InterestsAction.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (interests_ == null) {
              Interests = new global::Common.Entity.V1.InterestsElement();
            }
            input.ReadMessage(Interests);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the InterestsAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("SET")] Set = 0,
        [pbr::OriginalName("UNSET")] Unset = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
