// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: subscription_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mobile.Entity.V1 {

  /// <summary>Holder for reflection information generated from subscription_service.proto</summary>
  public static partial class SubscriptionServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for subscription_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SubscriptionServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpzdWJzY3JpcHRpb25fc2VydmljZS5wcm90bxIQbW9iaWxlLmVudGl0eS52",
            "MRoSY29tbW9uX21vZGVsLnByb3RvGhlwcm90b2J1Zl92YWxpZGF0aW9uLnBy",
            "b3RvGh1lbnRpdHkvdjEvZW50aXR5X2NvbW1vbi5wcm90bxojZW50aXR5L3Yx",
            "L3N1YnNjcmlwdGlvbl9jb21tb24ucHJvdG8iSwoXU3luY015Um9zdGVyRGF0",
            "YVJlcXVlc3QSMAoFdG9rZW4YASABKAsyIS5jb21tb24uZW50aXR5LnYxLlJv",
            "c3RlclN5bmNUb2tlbiKPAgoYU3luY015Um9zdGVyRGF0YVJlc3BvbnNlEkEK",
            "BnJlc3VsdBgBIAEoDjIxLm1vYmlsZS5lbnRpdHkudjEuU3luY015Um9zdGVy",
            "RGF0YVJlc3BvbnNlLlJlc3VsdBI8Cgtyb3N0ZXJfZGF0YRgCIAMoCzIdLmNv",
            "bW1vbi5lbnRpdHkudjEuUm9zdGVyRW50cnlCCMqdJQSAAfQDEjAKBXRva2Vu",
            "GAMgASgLMiEuY29tbW9uLmVudGl0eS52MS5Sb3N0ZXJTeW5jVG9rZW4SEAoI",
            "aGFzX21vcmUYBCABKAgiLgoGUmVzdWx0EgYKAk9LEAASDwoLTk9UX0FMTE9X",
            "RUQQARILCgdERUxBWUVEEAIyeQoMU3Vic2NyaXB0aW9uEmkKEFN5bmNNeVJv",
            "c3RlckRhdGESKS5tb2JpbGUuZW50aXR5LnYxLlN5bmNNeVJvc3RlckRhdGFS",
            "ZXF1ZXN0GioubW9iaWxlLmVudGl0eS52MS5TeW5jTXlSb3N0ZXJEYXRhUmVz",
            "cG9uc2VCcAoiY29tLmtpay5lbnRpdHkuc3Vic2NyaXB0aW9uLm1vYmlsZVpK",
            "Z2l0aHViLmNvbS9raWtpbnRlcmFjdGl2ZS94aXBoaWFzLWFwaS1tb2JpbGUv",
            "Z2VuZXJhdGVkL2dvL2VudGl0eS92MTtlbnRpdHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonModelReflection.Descriptor, global::Kik.Validation.ProtobufValidationReflection.Descriptor, global::Common.Entity.V1.EntityCommonReflection.Descriptor, global::Common.Entity.V1.SubscriptionCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mobile.Entity.V1.SyncMyRosterDataRequest), global::Mobile.Entity.V1.SyncMyRosterDataRequest.Parser, new[]{ "Token" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mobile.Entity.V1.SyncMyRosterDataResponse), global::Mobile.Entity.V1.SyncMyRosterDataResponse.Parser, new[]{ "Result", "RosterData", "Token", "HasMore" }, null, new[]{ typeof(global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SyncMyRosterDataRequest : pb::IMessage<SyncMyRosterDataRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SyncMyRosterDataRequest> _parser = new pb::MessageParser<SyncMyRosterDataRequest>(() => new SyncMyRosterDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SyncMyRosterDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mobile.Entity.V1.SubscriptionServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataRequest(SyncMyRosterDataRequest other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataRequest Clone() {
      return new SyncMyRosterDataRequest(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Common.Entity.V1.RosterSyncToken token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.RosterSyncToken Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SyncMyRosterDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SyncMyRosterDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SyncMyRosterDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          Token = new global::Common.Entity.V1.RosterSyncToken();
        }
        Token.MergeFrom(other.Token);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              Token = new global::Common.Entity.V1.RosterSyncToken();
            }
            input.ReadMessage(Token);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (token_ == null) {
              Token = new global::Common.Entity.V1.RosterSyncToken();
            }
            input.ReadMessage(Token);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SyncMyRosterDataResponse : pb::IMessage<SyncMyRosterDataResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SyncMyRosterDataResponse> _parser = new pb::MessageParser<SyncMyRosterDataResponse>(() => new SyncMyRosterDataResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SyncMyRosterDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mobile.Entity.V1.SubscriptionServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataResponse(SyncMyRosterDataResponse other) : this() {
      result_ = other.result_;
      rosterData_ = other.rosterData_.Clone();
      token_ = other.token_ != null ? other.token_.Clone() : null;
      hasMore_ = other.hasMore_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncMyRosterDataResponse Clone() {
      return new SyncMyRosterDataResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result result_ = global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "roster_data" field.</summary>
    public const int RosterDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Common.Entity.V1.RosterEntry> _repeated_rosterData_codec
        = pb::FieldCodec.ForMessage(18, global::Common.Entity.V1.RosterEntry.Parser);
    private readonly pbc::RepeatedField<global::Common.Entity.V1.RosterEntry> rosterData_ = new pbc::RepeatedField<global::Common.Entity.V1.RosterEntry>();
    /// <summary>
    /// Roster data returned in batches up to 500 or 100KiB (protobuf serialized)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Common.Entity.V1.RosterEntry> RosterData {
      get { return rosterData_; }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 3;
    private global::Common.Entity.V1.RosterSyncToken token_;
    /// <summary>
    /// New token to be used in subsequent call.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Entity.V1.RosterSyncToken Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "has_more" field.</summary>
    public const int HasMoreFieldNumber = 4;
    private bool hasMore_;
    /// <summary>
    /// Simply indicate the client should continue to pull with token above
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMore {
      get { return hasMore_; }
      set {
        hasMore_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SyncMyRosterDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SyncMyRosterDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!rosterData_.Equals(other.rosterData_)) return false;
      if (!object.Equals(Token, other.Token)) return false;
      if (HasMore != other.HasMore) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok) hash ^= Result.GetHashCode();
      hash ^= rosterData_.GetHashCode();
      if (token_ != null) hash ^= Token.GetHashCode();
      if (HasMore != false) hash ^= HasMore.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      rosterData_.WriteTo(output, _repeated_rosterData_codec);
      if (token_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Token);
      }
      if (HasMore != false) {
        output.WriteRawTag(32);
        output.WriteBool(HasMore);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      rosterData_.WriteTo(ref output, _repeated_rosterData_codec);
      if (token_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Token);
      }
      if (HasMore != false) {
        output.WriteRawTag(32);
        output.WriteBool(HasMore);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += rosterData_.CalculateSize(_repeated_rosterData_codec);
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (HasMore != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SyncMyRosterDataResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result.Ok) {
        Result = other.Result;
      }
      rosterData_.Add(other.rosterData_);
      if (other.token_ != null) {
        if (token_ == null) {
          Token = new global::Common.Entity.V1.RosterSyncToken();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.HasMore != false) {
        HasMore = other.HasMore;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            rosterData_.AddEntriesFrom(input, _repeated_rosterData_codec);
            break;
          }
          case 26: {
            if (token_ == null) {
              Token = new global::Common.Entity.V1.RosterSyncToken();
            }
            input.ReadMessage(Token);
            break;
          }
          case 32: {
            HasMore = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Mobile.Entity.V1.SyncMyRosterDataResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            rosterData_.AddEntriesFrom(ref input, _repeated_rosterData_codec);
            break;
          }
          case 26: {
            if (token_ == null) {
              Token = new global::Common.Entity.V1.RosterSyncToken();
            }
            input.ReadMessage(Token);
            break;
          }
          case 32: {
            HasMore = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SyncMyRosterDataResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        /// <summary>
        /// Token inconsistent with info on server
        /// </summary>
        [pbr::OriginalName("NOT_ALLOWED")] NotAllowed = 1,
        /// <summary>
        /// Roster data is not ready, client should delay for 10 mins and try again.
        /// </summary>
        [pbr::OriginalName("DELAYED")] Delayed = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
