// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: accounts/v1/user_info_shared.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Accounts.V1 {

  /// <summary>Holder for reflection information generated from accounts/v1/user_info_shared.proto</summary>
  public static partial class UserInfoSharedReflection {

    #region Descriptor
    /// <summary>File descriptor for accounts/v1/user_info_shared.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserInfoSharedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhY2NvdW50cy92MS91c2VyX2luZm9fc2hhcmVkLnByb3RvEhJjb21tb24u",
            "YWNjb3VudHMudjEaGXByb3RvYnVmX3ZhbGlkYXRpb24ucHJvdG8iUgoVRGlz",
            "cGxheU5hbWVDb21wb25lbnRzEh0KCmZpcnN0X25hbWUYASABKAlCCcqdJQUI",
            "ATD/ARIaCglsYXN0X25hbWUYAiABKAlCB8qdJQMw/wEqcgoNQWNjb3VudFN0",
            "YXR1cxIJCgVVTlNFVBAAEhkKFURFQUNUSVZBVEVEX0NPTkZJUk1FRBAKEhsK",
            "F0RFQUNUSVZBVEVEX1VOQ09ORklSTUVEEAkSDwoLVU5DT05GSVJNRUQQCxIN",
            "CglDT05GSVJNRUQQDEKMAQoWY29tLmtpay5hY2NvdW50cy5tb2RlbEITVXNl",
            "ckluZm9TaGFyZWRQcm90b1ABWlBnaXRodWIuY29tL2tpa2ludGVyYWN0aXZl",
            "L3hpcGhpYXMtbW9kZWwtY29tbW9uL2dlbmVyYXRlZC9nby9hY2NvdW50cy92",
            "MTthY2NvdW50c6ABAaICBVhJQUNDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kik.Validation.ProtobufValidationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.Accounts.V1.AccountStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Accounts.V1.DisplayNameComponents), global::Common.Accounts.V1.DisplayNameComponents.Parser, new[]{ "FirstName", "LastName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// The enum values in this enum are +10 from the enum values
  /// defined in kik-server. This is done because we don't want the
  /// default value to be DISABLED_CONFIRMED. Additionally, the offset
  /// between the two enum values must be large enough such that they
  /// do not overlap. Otherwise, setting the value directly could result
  /// in a status change (UNCONFIRMED may be serialized to CONFIRMED).
  ///
  /// Server definitions: https://github.com/kikinteractive/kik-server/blob/master/server/src/main/java/com/kik/utils/AccountUtils.java#L280
  ///
  /// Deactivated indicates that the account has been deactivated either by the user (recoverable) or
  /// foricibly terminated by support (non-recoverable). Confirmed indicates that the user has confirmed their email.
  /// </summary>
  public enum AccountStatus {
    [pbr::OriginalName("UNSET")] Unset = 0,
    /// <summary>
    ///  0 + 10
    /// </summary>
    [pbr::OriginalName("DEACTIVATED_CONFIRMED")] DeactivatedConfirmed = 10,
    /// <summary>
    /// -1 + 10
    /// </summary>
    [pbr::OriginalName("DEACTIVATED_UNCONFIRMED")] DeactivatedUnconfirmed = 9,
    /// <summary>
    ///  1 + 10
    /// </summary>
    [pbr::OriginalName("UNCONFIRMED")] Unconfirmed = 11,
    /// <summary>
    ///  2 + 10
    /// </summary>
    [pbr::OriginalName("CONFIRMED")] Confirmed = 12,
  }

  #endregion

  #region Messages
  /// <summary>
  /// DisplayNameComponents are the components that make up a user's display name.
  ///
  /// The display name can be generated by concat(first_name, " ", last_name),
  /// The display name components can be derived from a display name by splitting
  /// on the first space.
  ///
  /// Spaces are allowed in the first and last name components, but this can cause
  /// issues due to the way the components are derived from a display name
  /// (i.e. split on the first space).
  /// </summary>
  public sealed partial class DisplayNameComponents : pb::IMessage<DisplayNameComponents>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DisplayNameComponents> _parser = new pb::MessageParser<DisplayNameComponents>(() => new DisplayNameComponents());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DisplayNameComponents> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.Accounts.V1.UserInfoSharedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DisplayNameComponents() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DisplayNameComponents(DisplayNameComponents other) : this() {
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DisplayNameComponents Clone() {
      return new DisplayNameComponents(this);
    }

    /// <summary>Field number for the "first_name" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_name" field.</summary>
    public const int LastNameFieldNumber = 2;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DisplayNameComponents);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DisplayNameComponents other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DisplayNameComponents other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
